import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'hr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

// Translation object
type TranslationMap = { [key: string]: string };

const translations: Record<Language, TranslationMap> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.dashboard': 'Dashboard',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    'nav.admin': 'Admin',
    'nav.memoryMap': 'Memory Map',
    
    // Home page
    'home.title': 'Croatian Historical Photos',
    'home.subtitle': 'Preserve and share Croatia\'s rich photographic heritage',
    'home.description': 'Discover historical photographs from across Croatia. Share your own family photos and help preserve our cultural memory for future generations.',
    'home.upload': 'Upload Photo',
    'home.explore': 'Explore Gallery',
    'home.recent': 'Recent Photos',
    'home.reconnectTitle': 'Reconnect with Your Heritage',
    'home.discoverTitle': 'Discover Places',
    'home.discoverDesc': 'Search for any city or village in Croatia and explore its visual history on our interactive map.',
    'home.preserveTitle': 'Preserve Memories',
    'home.preserveDesc': 'Upload and share historical photos and videos from your family archives.',
    'home.connectTitle': 'Connect People',
    'home.connectDesc': 'Tag individuals, share stories, and reconnect with your community.',
    'home.exploreCroatiaTitle': 'Explore Croatia Through Time',
    'home.exploreCroatiaDesc': 'Discover historical photos geographically and see how your favorite places looked throughout history.',
    'home.exploreMemoryMap': 'Explore Memory Map',
    'home.glimpseTitle': 'Glimpse into the Past',
    'home.glimpseDesc': 'Browse through our collection of historical photos from various Croatian locations.',
    'home.startJourneyTitle': 'Start Your Journey Through Time',
    'home.startJourneyDesc': 'Join our community and help preserve the visual history of Croatia for future generations.',
    
    // Photo Detail Page
    'photoDetail.loading': 'Loading memory...',
    'photoDetail.notFound': 'Photo not found',
    'photoDetail.notFoundDesc': 'The requested memory could not be found.',
    'photoDetail.returnHome': 'Return to Homepage',
    'photoDetail.aboutPhoto': 'About this photo',
    'photoDetail.year': 'Year',
    'photoDetail.author': 'Author',
    'photoDetail.location': 'Location',
    'photoDetail.uploadedBy': 'Uploaded by',
    'photoDetail.on': 'on',
    'photoDetail.taggedPeople': 'Tagged People',
    'photoDetail.historicalContext': 'Historical Context',
    'photoDetail.relatedPhotos': 'Related Photos',
    'photoDetail.morePhotosFrom': 'More Photos from',
    'photoDetail.views': 'views',
    'photoDetail.likes': 'likes',
    'photoDetail.likePhoto': 'Like Photo',
    'photoDetail.unlikePhoto': 'Unlike Photo',
    'photoDetail.signInToLike': 'Sign In to Like',
    'photoDetail.signInMessage': 'Please sign in to like photos and interact with memories',
    'photoDetail.tagPerson': 'Tag Person',
    'photoDetail.clickToPosition': 'Click on the photo to position the tag',
    'photoDetail.personName': 'Person\'s name',
    'photoDetail.saveTag': 'Save Tag',
    'photoDetail.cancel': 'Cancel',
    'photoDetail.positionSelected': 'Position selected. Please enter a name for the tag.',
    'photoDetail.enterNameAndPosition': 'Please enter a name and select a position on the image',
    'photoDetail.taggedSuccess': 'Tagged {name} in the photo! The tag will be visible after admin approval.',
    'photoDetail.tagSaveFailed': 'Failed to add tag',
    'photoDetail.commentAdded': 'Comment added successfully!',
    'photoDetail.commentFailed': 'Failed to add comment',
    'photoDetail.photoLiked': 'Photo liked!',
    'photoDetail.photoUnliked': 'Photo unliked!',
    'photoDetail.likeFailed': 'Failed to update like',
    'photoDetail.historicalContextDesc': 'This period marked significant developments in the local history of {location}. Many similar photographs from this era document the changing landscape and daily life of inhabitants.',
    'photoDetail.defaultDescription': 'This historical photograph from {year} shows {description} in {location}. It was contributed to the Vremeplov.hr archive by {author}.',
    'photoDetail.tagPending': 'Tagged {name}! Tag is pending admin approval.',
    // Upload
    'upload.title': 'Share Historical Photo',
    'upload.select': 'Select Photo',
    'upload.drag': 'Drag and drop your photo here, or click to select',
    'upload.year': 'Year',
    'upload.author': 'Author/Photographer',
    'upload.description': 'Short Description',
    'upload.story': 'Detailed Story',
    'upload.submit': 'Upload Photo',
    'upload.cancel': 'Cancel',
    'upload.success': 'Photo uploaded successfully!',
    'upload.error': 'Failed to upload photo',
    'upload.offline': 'You are offline',
    'upload.tagPerson': 'Tag Person',
    'upload.enterName': 'Enter person\'s name',
    'upload.saveTag': 'Save Tag',
    'upload.cancelTag': 'Cancel',
  "upload.tierNewUser": "New User",
  "upload.tierVerified": "Verified User",
  "upload.tierContributor": "Contributor",
  "upload.tierPowerUser": "Power User",
  "upload.dailyLimit": "Daily limit",
  "upload.uploadedToday": "Uploaded today",
  "upload.remaining": "Remaining",
  "upload.limitReached": "Daily Limit Reached",
  "upload.limitReachedMessage": "You've reached your daily limit. Try again tomorrow after midnight!",
  "upload.nextTierProgress": "Progress to next tier",
  "upload.nextTierInfo.newUser": "{needed} more approved photos to reach Verified status (3 photos/day)",
"upload.nextTierInfo.verified": "{needed} more approved photos to reach Contributor status (5 photos/day)",
"upload.nextTierInfo.contributor": "{needed} more approved photos to reach Power User status (10 photos/day)",
"upload.nextTierInfo.maxTier": "You already have Power User status",
"upload.mustSelectAddress": "Please select an address from the list before continuing.",
    // Gallery
    'gallery.noPhotos': 'No photos yet',
    'gallery.noPhotosDesc': 'Be the first to share a historical photo and help preserve Croatian heritage!',
    'gallery.loading': 'Loading photos...',
    
    // Photo detail
    'photo.year': 'Year',
    'photo.author': 'Author',
    'photo.location': 'Location',
    'photo.story': 'Story',
    'photo.taggedPeople': 'Tagged People',
    'photo.comments': 'Comments',
    'photo.addComment': 'Add Comment',

    // Photo tag instructions
    'photo.tag.tip.mobile': '💡 Tip (mobile): Tap on the photo to see tagged persons',
'photo.tag.tip.desktop': '💡 Tip (desktop): Hover over the photo to see tagged persons',
'photo.tag.pendingInfo': 'Info: You have tags pending administrator approval. Orange dots indicate your pending tags.',

    // Auth
    'auth.signInGoogle': 'Sign in with Google',
    'auth.signOut': 'Sign Out',
    'auth.signInSuccess': 'Successfully signed in!',
    'auth.signOutSuccess': 'Successfully signed out!',
    'auth.adminLogin': 'Admin Login',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.adminSignInSuccess': 'Successfully signed in as admin!',

    
    // Common
    'common.of': 'of',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.required': 'Required',
    'common.optional': 'Optional',
    
    // Footer
    'footer.about': 'About',
    'footer.contact': 'Contact',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.rights': 'All rights reserved',
    'footer.tagline': 'Preserving Croatian heritage, one memory at a time.',

     // SearchBar
    'search.placeholder': 'Search for a city or village...',
    'search.button': 'Search',
    'search.inputPlaceholder': 'Search location...',
    'search.noLocations': 'No locations found',

    // Location stranica
    'location.exploreHistory': 'Explore the history through photos and memories',
    'location.photos': 'photos',
    'location.addMemory': 'Add Memory',
    'location.signInToAdd': 'Sign In to Add Memory',
    'location.searchPlaceholder': 'Search photos, descriptions, authors, or tags...',
    'location.filters': 'Filters',
    'location.clear': 'Clear',
    'location.timePeriod': 'Time Period',
    'location.allYears': 'All years',
    'location.photoType': 'Photo Type',
    'location.sortBy': 'Sort By',
    'location.showing': 'Showing',
    'location.matching': 'matching',
    'location.from': 'from',
    'location.in': 'in',
    'location.noPhotosFound': 'No photos found',
    'location.tryAdjusting': 'Try adjusting your filters or search terms.',
    'location.beFirst': 'Be the first to share a historical photo of this location!',
    'location.clearAllFilters': 'Clear all filters',
    'location.loadingMemories': 'Loading memories...',
    'location.loadMoreMemories': 'Load More Memories',
    'location.uploadSuccess': 'Photo uploaded successfully! It will appear after admin review.',

    // Photo types
    'photoType.allTypes': 'All Types',
    'photoType.street': 'Street Scenes', 
    'photoType.building': 'Buildings',
    'photoType.people': 'People',
    'photoType.event': 'Events',
    'photoType.nature': 'Nature',
    
    // Sort options
    'sort.newest': 'Newest First',
    'sort.oldest': 'Oldest First',
    'sort.popular': 'Most Popular',
    'sort.yearNewest': 'Year (Newest)',
    'sort.yearOldest': 'Year (Oldest)',
    
    // PhotoUpload komponenta
    'upload.addPhotoTo': 'Add Historical Photo to',
    'upload.clickToUpload': 'Click to upload a historical photo',
    'upload.fileTypes': 'PNG, JPG, JPEG up to 20MB',
    'upload.specificAddress': 'Specific Address in',
    'upload.optional': '(Optional)',
    'upload.searchAddress': 'Search for street, landmark, or building...',
    'upload.trySearching': 'Try searching',
    'upload.selectYear': 'Select year',
    'upload.whoTookPhoto': 'Who took this photo?',
    'upload.location': 'Location',
    'upload.briefDescription': 'Brief description of the photo',
    'upload.detailedStory': 'Detailed Story (Optional)',
    'upload.shareStory': 'Share the story behind this photo, historical context, or personal memories...',
    'upload.fillRequired': 'Fill Required Fields',
    'upload.shareMemory': 'Share Memory',
    'upload.noConnection': 'No Connection',
    'upload.uploading': 'Uploading...',
    'upload.photoType': 'Photo Type',
'upload.selectPhotoType': 'Select photo type',
// Add to LanguageContext.tsx - ENGLISH (en)
'upload.locationFound': 'Address location found!',
'upload.coordinatesNotFound': 'Could not find exact coordinates for this address',
'upload.selectExactLocation': 'Select exact location for {street} {number}',
'upload.locationSet': 'Location set for {street} {number}!',
'upload.selectNewLocation': 'Select new location for {street} {number}',
'upload.canSearchAgain': 'You can search for address again',
'upload.compressing': 'Compressing image...',
'upload.compressed': 'Image compressed: {original}MB → {compressed}MB ({reduction}% smaller)',
'upload.optimalSize': 'Image is optimal size',
'upload.successWithLocation': 'Photo uploaded successfully with location {address}! It will be reviewed and published soon.',
// ✅ Address search UI
  'upload.searchingAddresses': 'Searching for addresses...',
  'upload.foundAddresses': 'Found {count} address',
  'upload.foundAddressesPlural': 'Found {count} addresses',
  'upload.cached': 'cached',
  'upload.noAddressesFound': 'No addresses found for',
  'upload.waitingDebounce': 'Waiting...',
  'upload.cacheEntries': 'Cache: {count} entries',
  
  // ✅ Manual positioning
  'upload.streetFound': '{street} found! Select exact location for number {number}',
  'upload.clickOnMap': 'Click on the map where this photo is exactly located',
  'upload.zoomTip': 'Tip: Zoom in for greater accuracy. Marker will appear where you click.',
  
  // ✅ Location confirmation
  'upload.locationSetTitle': 'Location set: {address}',
  'upload.coordinates': 'Coordinates',
  'upload.changeLocation': 'Change',
  'upload.selectedPhotoLocation': 'Selected photo location',
  'upload.locationFoundCoords': 'Location found: {latitude}, {longitude}',


    // Text
    'text.characterCounter': 'characters',



// en.json
'nav.memoryMapShort': 'Map',

// English translations (en)
'comments.title': 'Comments ({count})',
'comments.placeholder': 'Share your memories or knowledge about this photo...',
'comments.postComment': 'Post Comment',
'comments.signInMessage': 'Sign in to share your memories and comments',
'comments.signInToComment': 'Sign In to Comment',
'comments.signInSuccess': 'Successfully signed in! You can now comment.',
'comments.signInError': 'Failed to sign in. Please try again.',
'comments.commentAdded': 'Your comment has been added!',
'comments.noComments': 'No comments yet. Be the first to share your thoughts!',
'comments.author': 'Author',
'comments.emptyComment': 'Comment cannot be empty',
'comments.mustBeSignedIn': 'You must be signed in',
'comments.loadError': 'Error loading comments',
'comments.postError': 'Error posting comment',
'comments.loading': 'Loading comments...',

'admin.photoApproved': 'Photo approved successfully',
'admin.photoRejected': 'Photo rejected and deleted',
'admin.photoUpdated': 'Photo updated successfully',
'admin.photoDeleted': 'Photo deleted successfully',
'admin.tagApproved': 'Tag approved successfully',
'admin.tagRejected': 'Tag rejected and deleted',
'admin.tagUpdated': 'Tag updated successfully',
'admin.adminModeExited': 'Exited admin mode successfully',
'admin.imageUploaded': 'Image uploaded successfully!',

// English translations (add to the 'en' object):
'locationMap.photoLocation': 'Photo Location',
'locationMap.viewOnMap': 'View on Map',
'locationMap.viewPhoto': 'View photo',
'locationMap.location': 'Location',
'locationMap.address': 'Address',
'locationMap.nearbyPhotos': 'Nearby photos',

// English translations (add to the 'en' object):
'mapView.memoryMap': 'Memory Map',
'mapView.noPhotos': 'No photos with coordinates found yet',
'mapView.exploreCroatian': 'Explore Croatian heritage through interactive map',
'mapView.loadingMemoryMap': 'Loading memory map...',
'mapView.noLocatedPhotos': 'No Located Photos Yet',
'mapView.photosWillAppear': 'Photos will appear on the map once they are uploaded with specific addresses.',
'mapView.addPhotosTo': 'Add Photos to {location}',
'mapView.filters': 'Filters:',
'mapView.allDecades': 'All decades',
'mapView.searchByLocation': 'Search by location or address...',
'mapView.showing': 'Showing {filtered} of {total} photos',
'mapView.photosOnMap': 'Photos on Map',
'mapView.viewDetails': 'View Details',
'mapView.photosInArea': '{count} Photos in this area',
'mapView.morePhotos': '+{count} more photos',
'mapView.locatedPhotos': 'Located Photos',
'mapView.cities': 'Cities',
'mapView.specificAddresses': 'Specific Addresses',
'mapView.differentDecades': 'Different Decades',
'mapView.debugInfo': '🔍 Debug Info:',
'mapView.totalPhotos': 'Total photos:',
'mapView.filtered': 'Filtered:',
'mapView.currentZoom': 'Current zoom:',
'mapView.clusters': 'Clusters:',
'mapView.individualMarkers': 'Individual markers:',
'mapView.howClusteringWorks': '📍 How clustering works',
'mapView.clusteringDesc1': '• When multiple photos are close together, they group into numbered clusters',
'mapView.clusteringDesc2': '• Click on a cluster to see all photos in that area',
'mapView.clusteringDesc3': '• Zoom in to see individual photo markers',
'mapView.clusteringDesc4': '• Upload more photos to the same address to see clustering in action!',

// About page
'about.title': 'About Vremeplov',
'about.subtitle': 'Preserving Croatian heritage, one memory at a time',
'about.ourMission': 'Our Mission',
'about.missionText1': 'Vremeplov.hr is a digital platform dedicated to preserving and sharing the rich visual history of Croatian cities and villages. We believe that every photograph tells a story, and every story deserves to be preserved for future generations.',
'about.missionText2': 'Our mission is to create a comprehensive archive of historical photographs from across Croatia, making these precious memories accessible to everyone while fostering a deeper connection to our heritage.',
'about.howWeHelp': 'How We Help Communities',
'about.digitalPreservation': 'Digital Preservation',
'about.digitalPreservationDesc': 'We provide a secure, digital home for historical photographs that might otherwise be lost to time.',
'about.localHistory': 'Local History Documentation',
'about.localHistoryDesc': 'Each location gets its own dedicated space, creating comprehensive visual histories of Croatian places.',
'about.communityConnection': 'Community Connection',
'about.communityConnectionDesc': 'People can tag relatives, share stories, and connect with others who share their heritage.',
'about.culturalHeritage': 'Cultural Heritage',
'about.culturalHeritageDesc': 'We help communities maintain their cultural identity by preserving visual memories.',
'about.aboutDeveloper': 'About the Developer',
'about.developerText1': 'Vremeplov.hr was created by Kruno Žagar, a passionate developer committed to preserving Croatian heritage through technology. Understanding the importance of our cultural history and the risk of losing precious memories, Kruno developed this platform to ensure that future generations can explore and connect with their roots.',
'about.developerText2': 'This project represents a personal commitment to giving back to the community by providing a valuable service that helps preserve our shared cultural heritage.',
'about.getInvolved': 'Get Involved',
'about.getInvolvedText': 'Help us build the most comprehensive archive of Croatian historical photographs. Your contributions make a difference in preserving our heritage.',
'about.startContributing': 'Start Contributing',

// Privacy page
'privacy.title': 'Privacy Policy',
'privacy.subtitle': 'How we protect and handle your data',
'privacy.dataCollection': 'Data Collection and Storage',
'privacy.dataCollectionText1': 'When you upload photos to Vremeplov.hr, we collect and store the following information:',
'privacy.dataCollectionList1': 'Historical photographs you choose to share',
'privacy.dataCollectionList2': 'Photo metadata (year, location, description, author)',
'privacy.dataCollectionList3': 'Comments and tags you add to photos',
'privacy.dataCollectionList4': 'Basic usage analytics to improve the platform',
'privacy.dataCollectionText2': 'All uploaded photos are stored securely in our database and are made publicly available on the platform to fulfill our mission of preserving Croatian heritage. By uploading content, you grant permission for it to be displayed on Vremeplov.hr.',
'privacy.dataProtection': 'Data Protection',
'privacy.dataProtectionText1': 'We take the security of your data seriously. All uploads are processed through secure connections and stored using industry-standard security measures.',
'privacy.dataProtectionText2': 'We do not sell, trade, or otherwise transfer your personal information to third parties. Your data is used solely for the purpose of operating and improving Vremeplov.hr.',
'privacy.contentRemoval': 'Content Removal',
'privacy.contentRemovalText1': 'If you need to remove photos or other content you\'ve uploaded, you can request deletion by contacting us with a valid reason. We will review each request and remove content when appropriate.',
'privacy.contentRemovalText2': 'Valid reasons for content removal include:',
'privacy.contentRemovalList1': 'Copyright concerns or ownership disputes',
'privacy.contentRemovalList2': 'Privacy concerns regarding individuals in photos',
'privacy.contentRemovalList3': 'Inaccurate or misleading information',
'privacy.contentRemovalList4': 'Personal or family requests for removal',
'privacy.privacyQuestions': 'Privacy Questions',
'privacy.privacyQuestionsText': 'If you have questions about this privacy policy or concerns about your data, please contact us at:',
'privacy.policyUpdates': 'Policy Updates',
'privacy.policyUpdatesText': 'This privacy policy may be updated from time to time. Any changes will be posted on this page with an updated revision date. Continued use of Vremeplov.hr after changes constitutes acceptance of the updated policy.',
'privacy.lastUpdated': 'Last updated: {date}',
'privacy.gdprRights': 'Your GDPR Rights',
'privacy.gdprRightsText': 'Under GDPR, you have the following rights:',
'privacy.rightAccess': 'Right to access your personal data',
'privacy.rightDelete': 'Right to delete your account and all associated data',
'privacy.rightExport': 'Right to export all your data',
'privacy.rightCorrect': 'Right to correct inaccurate data',
'privacy.rightsContact': 'To exercise these rights, please contact us at:',
'privacy.thirdPartyServices': 'Third-Party Services',
'privacy.thirdPartyText': 'We use the following third-party services:',
'privacy.firebaseDesc': 'Data hosting (Server location: EU - Belgium and Netherlands)',
'privacy.analyticsDesc': 'Website analytics',
'privacy.mapsDesc': 'Location display on maps',
'privacy.thirdPartyNote': 'Each service has its own privacy policy. We do not share your data with third parties except for the services listed above.',
'privacy.dataRetention': 'Data Retention Period',
'privacy.dataRetentionText': 'We retain data for the following periods:',
'privacy.retentionApproved': 'Approved photos: Permanently (as long as the platform exists)',
'privacy.retentionAccount': 'User account data: As long as the account is active',
'privacy.retentionUnapproved': 'Unapproved photos: Automatically deleted after 90 days',

// Terms page
'terms.title': 'Terms of Service',
'terms.subtitle': 'Rules and guidelines for using Vremeplov.hr',
'terms.acceptance': 'Acceptance of Terms',
'terms.acceptanceText': 'By accessing and using Vremeplov.hr, you accept and agree to be bound by these terms and conditions. If you do not agree to these terms, please do not use our platform.',
'terms.contentCopyright': 'Content and Copyright',
'terms.contentText1': 'When uploading content to Vremeplov.hr, you must ensure that:',
'terms.contentList1': 'You own the rights to the photographs or have permission to share them',
'terms.contentList2': 'The content is historically accurate to the best of your knowledge',
'terms.contentList3': 'Photos are appropriate and respectful to all individuals depicted',
'terms.contentList4': 'Content does not violate any third-party rights or applicable laws',
'terms.contentText2': 'By uploading content, you grant Vremeplov.hr a non-exclusive license to display, store, and share your contributions as part of our cultural heritage preservation mission.',
'terms.userResponsibilities': 'User Responsibilities',
'terms.userText1': 'As a user of Vremeplov.hr, you agree to:',
'terms.userList1': 'Provide accurate information when uploading photos and metadata',
'terms.userList2': 'Use the platform respectfully and not engage in harassment or inappropriate behavior',
'terms.userList3': 'Respect the privacy and dignity of individuals in historical photographs',
'terms.userList4': 'Report any content that violates these terms or appears inappropriate',
'terms.userList5': 'Not attempt to damage, disable, or impair the platform\'s functionality',
'terms.moderation': 'Content Moderation',
'terms.moderationText': 'We reserve the right to review and remove content that:',
'terms.moderationList1': 'Violates copyright or intellectual property rights',
'terms.moderationList2': 'Contains inappropriate or offensive material',
'terms.moderationList3': 'Is not relevant to Croatian historical documentation',
'terms.moderationList4': 'Includes personal information of third parties without consent',
'terms.moderationWarning': 'Repeated violations of these guidelines may result in permanent account suspension.',
'terms.copyrightLiability': 'Vremeplov.hr does not assume responsibility for copyright issues related to uploaded images. Users are solely responsible for ensuring they have the right to use and share the content they upload.',
'terms.prohibited': 'Prohibited Activities',
'terms.prohibitedText': 'The following activities are strictly prohibited on Vremeplov.hr:',
'terms.prohibitedList1': 'Uploading copyrighted material without permission',
'terms.prohibitedList2': 'Sharing false or misleading historical information',
'terms.prohibitedList3': 'Uploading inappropriate, offensive, or harmful content',
'terms.prohibitedList4': 'Attempting to hack, spam, or otherwise misuse the platform',
'terms.prohibitedList5': 'Commercial use without explicit permission',
'terms.availability': 'Platform Availability',
'terms.availabilityText': 'While we strive to maintain 24/7 availability, Vremeplov.hr may occasionally be unavailable due to maintenance, updates, or technical issues. We are not liable for any inconvenience caused by temporary unavailability.',
'terms.liability': 'Limitation of Liability',
'terms.liabilityText': 'Vremeplov.hr is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the platform, including but not limited to data loss, service interruptions, or inaccuracies in user-contributed content.',
'terms.questionsAbout': 'Questions About Terms',
'terms.questionsText': 'If you have questions about these terms of service, please contact us at',
'terms.termsUpdates': 'Terms Updates',
'terms.termsUpdatesText': 'These terms may be updated from time to time. Changes will be posted on this page. Continued use of the platform after changes constitutes acceptance of the updated terms.',

// Contact page
'contact.title': 'Contact Us',
'contact.subtitle': 'Get in touch with the Vremeplov.hr team',
'contact.getInTouch': 'Get in Touch',
'contact.getInTouchText': 'We\'d love to hear from you! Whether you have questions, suggestions, or need help, we\'re here to assist you.',
'contact.ourEmail': 'Our dedicated email for all Vremeplov.hr inquiries',
'contact.whatCanWeHelp': 'What Can We Help You With?',
'contact.technicalSupport': 'Technical Support',
'contact.techList1': '• Issues uploading photos',
'contact.techList2': '• Website functionality problems',
'contact.techList3': '• Account or login assistance',
'contact.techList4': '• Mobile compatibility issues',
'contact.contentManagement': 'Content Management',
'contact.contentList1': '• Request photo removal',
'contact.contentList2': '• Report inappropriate content',
'contact.contentList3': '• Correct photo information',
'contact.contentList4': '• Copyright concerns',
'contact.partnership': 'Partnership & Collaboration',
'contact.partnershipList1': '• Museum partnerships',
'contact.partnershipList2': '• Community collaborations',
'contact.partnershipList3': '• Educational institution projects',
'contact.partnershipList4': '• Media and press inquiries',
'contact.generalFeedback': 'General Feedback',
'contact.feedbackList1': '• Suggestions for improvement',
'contact.feedbackList2': '• Feature requests',
'contact.feedbackList3': '• Share your story',
'contact.feedbackList4': '• General questions about the project',
'contact.responseTime': 'Response Time',
'contact.responseTimeText': 'We typically respond to all inquiries within 2-5 business days. For urgent issues (content removal or inappropriate content reports), please mark your email subject with "URGENT" and we will prioritize your request.',
'contact.urgentRequests': 'Urgent Requests',
'contact.urgentRequestsText': 'For urgent content removal or reporting inappropriate images, please include "URGENT" in your email subject line, and we will process it with priority.',
'contact.otherWays': 'Other Ways to Connect',
'contact.otherWaysText': 'While email is our primary contact method, you can also reach out through our social media channels or community forums when they become available.',
'contact.newsletter': 'Follow our development and updates by subscribing to our newsletter (coming soon)',

// FAQ page
'faq.title': 'Frequently Asked Questions',
'faq.subtitle': 'Find answers to common questions about Vremeplov.hr',
'faq.uploadModeration': 'Upload & Moderation',
'faq.q1': 'Why can I only upload 1 photo per day?',
'faq.a1': 'New users have a limit of 1 photo per day. After the admin approves 5 photos, you automatically get Verified status (3 photos/day). Continue contributing to unlock higher tiers: Contributor (5/day) and Power User (10/day).',
'faq.q2': 'Why hasn\'t my photo been published yet?',
'faq.a2': 'All photos go through manual moderation to ensure archive quality. We typically approve photos within 24-48 hours. You\'ll receive a notification when your photo is approved.',
'faq.q3': 'What if the admin rejects my photo?',
'faq.a3': 'Reasons may include: poor quality, not relevant to Croatia, copyrighted material, or missing information. You can re-upload with corrections.',
'faq.copyrightOwnership': 'Copyright & Ownership',
'faq.q4': 'Can I upload old photos from my family album?',
'faq.a4': 'YES, if you own the photos or have the owner\'s permission. Do not upload photos from the internet or other sources without permission.',
'faq.q5': 'What if someone uploaded my photo without permission?',
'faq.a5': 'Contact us at vremeplov.app@gmail.com with "URGENT" in the subject and we will remove the photo immediately.',
'faq.locationAddress': 'Location & Addresses',
'faq.q6': 'Do I have to add an address when uploading?',
'faq.a6': 'NO, the address is optional. But if you add an exact address, your photo will be visible on the Memory Map.',
'faq.q7': 'I can\'t find my street in the search, what now?',
'faq.a7': 'Try a broader search (e.g., just the city name), or upload without an address. You can add the address in the description field.',
'faq.accountTiers': 'Account & Tiers',
'faq.q8': 'How can I increase my daily limit?',
'faq.a8': 'Tier system: NEW_USER (1/day) → Upload 5 approved photos → VERIFIED (3/day) → Upload 15 approved photos → CONTRIBUTOR (5/day) → Upload 30 approved photos → POWER_USER (10/day)',
'faq.q9': 'Why do I need a Google account?',
'faq.a9': 'Google Sign-In provides quick and secure login without additional passwords. We do not share your data with third parties.',
'faq.privacyData': 'Privacy & Data',
'faq.q10': 'Can I delete my account and all photos?',
'faq.a10': 'YES. Contact us via email and we will process your GDPR request within 30 days. All your photos and data will be permanently deleted.',
'faq.q11': 'Where are my photos stored?',
'faq.a11': 'Securely on Google Firebase servers in the EU region (Belgium/Netherlands), in compliance with GDPR.',
'faq.technical': 'Technical Issues',
'faq.q12': 'The website is slow or not working, what should I do?',
'faq.a12': 'Try refreshing the page, clearing your browser cache, or using a different browser. If the problem persists, contact us at vremeplov.app@gmail.com.',
'faq.stillHaveQuestions': 'Still have questions?',
'faq.contactUs': 'Contact us at',
'faq.andWeWillHelp': 'and we\'ll be happy to help!',

//UserProfile aka MyProfile
// English translations
// Profile page
'profile.achievements': 'Achievements',
'profile.followers': 'Followers',
'profile.following': 'Following',
'profile.photos': 'Photos',
'profile.statistics': 'Statistics',
'profile.activity': 'Recent Activity',
'profile.editProfile': 'Edit Profile',
'profile.follow': 'Follow',
'profile.displayName': 'Display Name',
'profile.bio': 'Bio',
'profile.joined': 'Joined',
'profile.displayNamePlaceholder': 'Your display name',
'profile.tellAboutYourself': 'Tell us about yourself...',
'profile.yourLocation': 'e.g. Zagreb, Croatia',
'profile.saveChanges': 'Save Changes',
'profile.cancel': 'Cancel',
'profile.contributionStats': 'Contribution Stats',
'profile.totalPhotos': 'Total Photos',
'profile.uniqueLocations': 'Unique Locations',
'profile.totalLikesReceived': 'Total Likes Received',
'profile.totalViews': 'Total Views',
'profile.achievementsEarned': 'Achievements Earned',
'profile.communityImpact': 'Community Impact',
'profile.avgLikesPerPhoto': 'Avg. Likes per Photo',
'profile.avgViewsPerPhoto': 'Avg. Views per Photo',
'profile.memberSince': 'Member Since',
'profile.noPhotosYet': 'No photos yet',
'profile.startSharing': 'Start sharing your historical photos to build your collection!',
'profile.userHasntShared': 'This user hasn\'t shared any photos yet.',
'profile.uploadFirstPhoto': 'Upload Your First Photo',
'profile.noRecentActivity': 'No recent activity',
'profile.startUploading': 'Start uploading photos and interacting with the community to see your activity here!',
'profile.collectionOverview': 'Collection Overview',
'profile.totalLikes': 'Total Likes',
'profile.locations': 'Locations',
'profile.unknown': 'Unknown',
'profile.loadingProfile': 'Loading profile...',
'profile.loadError': 'Failed to load user profile',
'profile.unfollowed': 'Unfollowed user',
'profile.nowFollowing': 'Now following user!',
'profile.followError': 'Failed to update follow status',
'profile.updateSuccess': 'Profile updated successfully!',
'profile.updateError': 'Failed to update profile',
'profile.statsFixed': 'User stats fixed successfully!',
'profile.statsError': 'Failed to fix user stats',
'profile.defaultBio': 'Passionate about preserving Croatian heritage through historical photography.',
'profile.editProfileDescription': 'Update your profile information below.',
'profile.loadMore': 'Load more activities',
'profile.loading': 'Loading...',
'profile.loadMoreError': 'Error loading activities',
'profile.loadMorePhotos': 'Load more photos',
'profile.photosLoaded': 'Loaded photos',

// Badge names
'profile.badgePhotographer': 'Photographer',
'profile.badgeHistorian': 'Local Historian',
'profile.badgeExplorer': 'Heritage Explorer',
'profile.badgePopular': 'Community Favorite',
'profile.badgeSocial': 'Social Butterfly',
'profile.badgeVeteran': 'Heritage Veteran',
'profile.badgeLegend': 'Heritage Legend',

// Activity translations
'profile.activityUploaded': 'uploaded a photo',
'profile.activityLiked': 'liked a photo',
'profile.activityFollowed': 'started following',
'profile.activityBadge': 'earned a badge',
'profile.activityComment': 'added a comment',
'profile.activityTagged': 'tagged someone in',

//Community
// English translations
// Community page
'community.leaderboard': 'Community Leaderboard',
'community.celebratingContributors': 'Celebrating our top heritage contributors',
'community.timePeriod': 'Time Period',
'community.allTime': 'All Time',
'community.thisYear': 'This Year',
'community.thisMonth': 'This Month',
'community.updatedDaily': 'Updated daily at midnight',
'community.mostPhotos': 'Most Photos',
'community.mostLiked': 'Most Liked',
'community.mostLocations': 'Most Locations',
'community.newMembers': 'New Members',
'community.places': 'Places',
'community.new': 'New',
'community.likes': 'Favorites',
'community.locations': 'locations',
'community.joined': 'joined',
'community.badge': 'badge',
'community.loadingLeaderboard': 'Loading leaderboard...',
'community.topContributorsByPhotos': 'Top Contributors by Photos',
'community.mostAppreciatedContributors': 'Most Appreciated Contributors',
'community.heritageExplorers': 'Heritage Explorers',
'community.welcomeNewMembers': 'Welcome New Members',
'community.communityStats': 'Community Stats',
'community.totalMembers': 'Total Members',
'community.photosShared': 'Photos Shared',
'community.locationsDocumented': 'Locations Documented',
'community.thisMonthsHighlights': 'This Month\'s Highlights',
'community.mostActiveLocation': 'Most Active Location',
'community.newPhotos': 'new photos',
'community.photoOfTheMonth': 'Photo of the Month',
'community.by': 'by',
'community.fromLastMonth': 'from last month',
'community.achievementSystem': 'Achievement System',
'community.earnBadges': 'Earn badges by contributing to our heritage collection:',
'community.photographer': 'Photographer: Upload your first photo',
'community.localHistorian': 'Local Historian: Share 10+ photos',
'community.heritageExplorer': 'Heritage Explorer: 5+ locations',
'community.communityFavorite': 'Community Favorite: 100+ likes',

'userProfile.myProfile': 'My Profile',
'userProfile.community': 'Community',
'userProfile.signOut': 'Sign Out',

'cityType.city': 'City',
    'cityType.municipality': 'Municipality',

    // ✅ ERROR MESSAGES - ENGLISH
    'errors.signInFailed': 'Failed to sign in',
    'errors.signOutFailed': 'Failed to sign out',
    'errors.signInRequired': 'Please sign in to like photos',
    'errors.adminModeExit': 'Failed to exit admin mode',
    'errors.adminModeEnter': 'Failed to enter admin mode',
    
    // Upload errors
    'errors.fillAllFields': 'Please fill in all fields and select an image',
    'errors.invalidImageType': 'Please select a valid image file (JPG, PNG, WEBP)',
    'errors.imageTooLarge': 'Image is too large (max 20MB). Please compress the image',
    'errors.uploadFailed': 'Upload failed: Storage permissions issue. Please try again.',
    'errors.uploadStorageFull': 'Upload failed: Storage quota exceeded. Please try again later.',
    'errors.uploadError': 'Upload failed: Poor internet connection. Please check your connection and try again.',
    'errors.compressionError': 'Image compression failed',
    'errors.addressSearchFailed': 'Failed to search addresses',
    'errors.fileRequired': 'Please select a file',
    'errors.offline': 'You are offline. Please check your internet connection',
    
    // Photo errors
    'errors.photoLoadFailed': 'Failed to load photos',
    'errors.photoLikeFailed': 'Failed to like photo',
    'errors.photoDeleteFailed': 'Failed to delete photo',
    'errors.photoUpdateFailed': 'Failed to update photo',
    'errors.photoApprovalFailed': 'Failed to approve photo',
    'errors.photoTagApprovalFailed': 'Failed to approve tag',
    'errors.photoTagRejectionFailed': 'Failed to reject tag',
    'errors.photoTagUpdateFailed': 'Failed to update tag',
    'errors.photoNotFound': 'Photo not found',
    'errors.photoAddFailed': 'Failed to add photo',
    
    // Comment errors
    'errors.commentError': 'Error posting comment',
    'errors.commentEmpty': 'Comment cannot be empty',
    'errors.commentSignInRequired': 'Please sign in to comment',
    'errors.commentLoadFailed': 'Failed to load comments',
    
    // Location errors
    'errors.locationLoadFailed': 'Failed to load location',
    
    // Admin errors
    'errors.adminDataLoadFailed': 'Failed to load admin data',
    
    // Profile errors
    'errors.profileLoadError': 'Failed to load profile',
    'errors.followError': 'Failed to follow user',
    'errors.updateError': 'Failed to update profile',
    'errors.statsError': 'Failed to load statistics',
    
    // Community errors
    'errors.loadFailed': 'Failed to load data',
    'errors.leaderboardLoadFailed': 'Failed to load leaderboard',
    
    // Photo details errors
    'errors.notFound': 'Photo not found',
    'errors.enterNameAndPosition': 'Please enter a name and select a position',
    'errors.tagSaveFailed': 'Failed to save tag',
    'errors.signInMessage': 'Please sign in to add tags',
    'errors.likeFailed': 'Failed to like photo',
    'errors.signInToLike': 'Please sign in to like photos',
    
    // Auth errors
    'errors.signInError': 'Failed to sign in. Please try again.',
    'errors.signInToAddMemory': 'Please sign in to add memories',

    

     "searching": "Searching...",
    "typing": "Typing...",
    "found": "found",
    "noResults": "No results",
    "foundAddresses": "Found {{count}} addresses",
    "foundAddresses_one": "Found {{count}} address",
    "cacheEntries": "Cache: {{count}} entries",
    "waiting": "Waiting...",


'notifications.title': 'Notifications',
'notifications.markAll': 'Mark all',
'notifications.viewAll': 'View all notifications',
'notifications.loading': 'Loading...',
'notifications.noNotifications': 'No new notifications',
'notifications.noNotificationsDesc': 'Your notifications will appear here',
'notifications.allRead': 'All notifications marked as read',
'notifications.markError': 'Error marking notifications',
'notifications.unknownPhoto': "Unknown Photo",


// Notification message parts
'notifications.commented': 'commented on your photo',
'notifications.liked': 'liked your photo',
'notifications.following': 'is now following you',
'notifications.tagged': 'tagged you in the photo',
'notifications.congratulations': 'Congratulations! You earned a badge:',
'notifications.yourPhoto': 'Your photo',
'notifications.approved': 'has been approved',
'notifications.rejected': 'was rejected',
'notifications.edited': 'has been edited',
'notifications.deleted': 'was deleted',
'notifications.tag': 'Tag of',
'notifications.yourCommentDeleted': 'Your comment was deleted',
'notifications.accountBanned': 'Your account has been banned',
'notifications.accountSuspended': 'Your account has been suspended',
'notifications.accountActive': 'Your account is active again. Welcome back!',
'notifications.suspensionLifted': 'Your account suspension has been lifted. Welcome back!',
'notifications.newNotification': 'New notification',
'notifications.notAvailable': 'Content not available',

// Time formatting
'notifications.time.justNow': 'just now',
'notifications.time.ago': '', // prazno za engleski jer ide "5 min ago"
'notifications.time.min': 'min ago',
'notifications.time.hours': 'h ago',
'notifications.time.days': 'd ago',

  },
  hr: {
    'notifications.notAvailable': 'Sadržaj nije dostupan',
'notifications.title': 'Obavijesti',
'notifications.markAll': 'Označi sve',
'notifications.viewAll': 'Prikaži sve obavijesti',
'notifications.loading': 'Učitavanje...',
'notifications.noNotifications': 'Nemaš novih obavijesti',
'notifications.noNotificationsDesc': 'Ovdje će se pojaviti tvoje obavijesti',
'notifications.allRead': 'Sve obavijesti označene kao pročitane',
'notifications.markError': 'Greška pri označavanju obavijesti',
'notifications.unknownPhoto': "Nepoznata fotografija",
// Notification message parts
'notifications.commented': 'je komentirao/la tvoju fotografiju',
'notifications.liked': 'je lajkao/la tvoju fotografiju',
'notifications.following': 'te sada prati',
'notifications.tagged': 'te označio/la na fotografiji',
'notifications.congratulations': 'Čestitamo! Zaradio/la si značku:',
'notifications.yourPhoto': 'Tvoja fotografija',
'notifications.approved': 'je odobrena',
'notifications.rejected': 'je odbijena',
'notifications.edited': 'je uređena',
'notifications.deleted': 'je obrisana',
'notifications.tag': 'Tag osobe',
'notifications.yourCommentDeleted': 'Tvoj komentar je obrisan',
'notifications.accountBanned': 'Tvoj račun je bannan',
'notifications.accountSuspended': 'Tvoj račun je suspendiran',
'notifications.accountActive': 'Tvoj račun je ponovo aktivan. Dobrodošao/la natrag!',
'notifications.suspensionLifted': 'Suspenzija tvog računa je uklonjena. Dobrodošao/la natrag!',
'notifications.newNotification': 'Nova obavijest',

// Time formatting
'notifications.time.justNow': 'upravo sad',
'notifications.time.ago': 'prije',
'notifications.time.min': ' min',
'notifications.time.hours': ' sat/a',
'notifications.time.days': ' dan/a',



"searching": "Pretraživanje...",
    "typing": "Tipkate...",
    "found": "pronađeno",
    "noResults": "Nema rezultata",
    "foundAddresses": "Pronađeno {{count}} adresa",
    "foundAddresses_one": "Pronađena {{count}} adresa",
    "cacheEntries": "Cache: {{count}} unosa",
    "waiting": "Čekanje...",


    'cityType.city': 'Grad',
    'cityType.municipality': 'Općina',
    // Navigation
    'nav.home': 'Početna',
    'nav.about': 'O nama',
    'nav.contact': 'Kontakt',
    'nav.dashboard': 'Kontrolna ploča',
    'nav.login': 'Prijava',
    'nav.logout': 'Odjava',
    'nav.admin': 'Admin',
    'nav.memoryMap': 'Karta sjećanja',
    
    // Home page
    'home.title': 'Hrvatske povijesne fotografije',
    'home.subtitle': 'Sačuvajte i podijelite bogatu fotografsku baštinu Hrvatske',
    'home.description': 'Otkrijte povijesne fotografije iz cijele Hrvatske. Podijelite svoje obiteljske fotografije i pomozite sačuvati našu kulturnu memoriju za buduće generacije.',
    'home.upload': 'Učitaj fotografiju',
    'home.explore': 'Istraži galeriju',
    'home.recent': 'Nedavne fotografije',
    'home.reconnectTitle': 'Povežite se sa svojom baštinom',
    'home.discoverTitle': 'Otkrijte mjesta',
    'home.discoverDesc': 'Pretražite bilo koji grad ili selo u hrvatskoj i istražite njegovu vizualnu povijest na našoj interaktivnoj karti.',
    'home.preserveTitle': 'Sačuvajte sjećanja',
    'home.preserveDesc': 'Učitajte i podijelite povijesne fotografije i videozapise iz svojih obiteljskih arhiva.',
    'home.connectTitle': 'Povežite ljude',
    'home.connectDesc': 'Označite osobe, podijelite priče i povežite se sa svojom zajednicom.',
    'home.exploreCroatiaTitle': 'Istražite Hrvatsku kroz vrijeme',
    'home.exploreCroatiaDesc': 'Otkrijte povijesne fotografije geografski i vidite kako su vaša omiljena mjesta izgledala kroz povijest.',
    'home.exploreMemoryMap': 'Istražite kartu sjećanja',
    'home.glimpseTitle': 'Pogled u prošlost',
    'home.glimpseDesc': 'Pregledajte našu kolekciju povijesnih fotografija iz različitih hrvatskih lokacija.',
    'home.startJourneyTitle': 'Započnite svoje putovanje kroz vrijeme',
    'home.startJourneyDesc': 'Pridružite se našoj zajednici i pomozite sačuvati vizualnu povijest Hrvatske za buduće generacije.',
    
    // hr.json
'nav.memoryMapShort': 'Karta',

    // Photo Detail Page
    'photoDetail.loading': 'Učitavanje sjećanja...',
    'photoDetail.notFound': 'Fotografija nije pronađena',
    'photoDetail.notFoundDesc': 'Traženo sjećanje nije moglo biti pronađeno.',
    'photoDetail.returnHome': 'Vrati se na početnu',
    'photoDetail.aboutPhoto': 'O ovoj fotografiji',
    'photoDetail.year': 'Godina',
    'photoDetail.author': 'Autor',
    'photoDetail.location': 'Lokacija',
    'photoDetail.uploadedBy': 'Učitao',
    'photoDetail.on': 'dana',
    'photoDetail.taggedPeople': 'Označene osobe',
    'photoDetail.historicalContext': 'Povijesni kontekst',
    'photoDetail.relatedPhotos': 'Povezane fotografije',
    'photoDetail.morePhotosFrom': 'Više fotografija iz',
    'photoDetail.views': 'pogleda',
    'photoDetail.likes': 'sviđanja',
    'photoDetail.likePhoto': 'Sviđa mi se',
    'photoDetail.unlikePhoto': 'Ne sviđa mi se',
    'photoDetail.signInToLike': 'Prijavite se za ocjenu',
    'photoDetail.signInMessage': 'Molimo prijavite se da biste mogli ocijeniti fotografije i komunicirati sa sjećanjima',
    'photoDetail.tagPerson': 'Označi osobu',
    'photoDetail.clickToPosition': 'Kliknite na fotografiju da postavite oznaku',
    'photoDetail.personName': 'Ime osobe',
    'photoDetail.saveTag': 'Spremi oznaku',
    'photoDetail.cancel': 'Odustani',
    'photoDetail.positionSelected': 'Pozicija je odabrana. Molimo unesite ime za oznaku.',
    'photoDetail.enterNameAndPosition': 'Molimo unesite ime i odaberite poziciju na slici',
    'photoDetail.taggedSuccess': 'Označena osoba {name} na fotografiji! Oznaka će biti vidljiva nakon odobrenja administratora.',
    'photoDetail.tagSaveFailed': 'Neuspješno dodavanje oznake',
    'photoDetail.commentAdded': 'Komentar je uspješno dodan!',
    'photoDetail.commentFailed': 'Neuspješno dodavanje komentara',
    'photoDetail.photoLiked': 'Fotografija označena kao sviđa!',
    'photoDetail.photoUnliked': 'Fotografija označena kao ne sviđa!',
    'photoDetail.likeFailed': 'Neuspješno ažuriranje ocjene',
    'photoDetail.historicalContextDesc': 'Ovo razdoblje je obilježilo značajan razvoj u lokalnoj povijesti mjesta {location}. Mnoge slične fotografije iz tog doba dokumentiraju mijenjajući se krajolik i svakodnevni život stanovnika.',
    'photoDetail.defaultDescription': 'Ova povijesna fotografija iz {year}. prikazuje {description} u {location}. Doprinijela ju je u arhiv Vremeplov.hr osoba {author}.',
    'photoDetail.tagPending': 'Označena osoba {name}! Oznaka čeka odobrenje admina.',
    // Upload
    'upload.title': 'Podijeli povijesnu fotografiju',
    'upload.select': 'Odaberi fotografiju',
    'upload.drag': 'Povuci i spusti fotografiju ovdje ili klikni za odabir',
    'upload.year': 'Godina',
    'upload.author': 'Autor/Fotograf',
    'upload.description': 'Kratki opis',
    'upload.story': 'Detaljna priča',
    'upload.submit': 'Učitaj fotografiju',
    'upload.cancel': 'Odustani',
    'upload.success': 'Fotografija je uspješno učitana!',
    'upload.error': 'Neuspješno učitavanje fotografije',
    'upload.offline': 'Niste povezani s internetom',
    'upload.tagPerson': 'Označi osobu',
    'upload.enterName': 'Unesite ime osobe',
    'upload.saveTag': 'Spremi oznaku',
    'upload.cancelTag': 'Odustani',
  "upload.tierNewUser": "Novi Korisnik",
  "upload.tierVerified": "Provjereni Korisnik",
  "upload.tierContributor": "Doprinositelj",
  "upload.tierPowerUser": "Power Korisnik",
  "upload.dailyLimit": "Dnevni limit",
  "upload.uploadedToday": "Uploadano danas",
  "upload.remaining": "Preostalo",
  "upload.limitReached": "Dnevni Limit Postignut",
  "upload.limitReachedMessage": "Dostigao si dnevni limit. Pokušaj sutra nakon ponoći!",
  "upload.nextTierProgress": "Napredak do sljedećeg nivoa",
  "upload.nextTierInfo.newUser": "Još {needed} odobrenih slika do Verified statusa (3 slike/dan)",
"upload.nextTierInfo.verified": "Još {needed} odobrenih slika do Contributor statusa (5 slika/dan)",
"upload.nextTierInfo.contributor": "Još {needed} odobrenih slika do Power User statusa (10 slika/dan)",
"upload.nextTierInfo.maxTier": "Već imaš Power User status",

    // Add to LanguageContext.tsx - CROATIAN (hr)
'upload.locationFound': 'Lokacija adrese pronađena!',
'upload.coordinatesNotFound': 'Nije moguće pronaći točne koordinate za ovu adresu',
'upload.selectExactLocation': 'Odaberite točnu lokaciju za {street} {number}',
'upload.locationSet': 'Lokacija postavljena za {street} {number}!',
'upload.selectNewLocation': 'Odaberite novu lokaciju za {street} {number}',
'upload.canSearchAgain': 'Možete ponovo pretražiti adresu',
'upload.compressing': 'Kompresiranje slike...',
'upload.compressed': 'Slika kompresovana: {original}MB → {compressed}MB ({reduction}% manje)',
'upload.optimalSize': 'Slika je optimalne veličine',
'upload.successWithLocation': 'Fotografija uspješno učitana s lokacijom {address}! Bit će pregledana i objavljena uskoro.',
"upload.mustSelectAddress": "Molimo odaberite adresu iz popisa prije nastavka.",
    
    // Gallery
    'gallery.noPhotos': 'Nema fotografija',
    'gallery.noPhotosDesc': 'Budite prvi koji će podijeliti povijesnu fotografiju i pomoći sačuvati hrvatsku baštinu!',
    'gallery.loading': 'Učitavanje fotografija...',
    
    // Photo detail
    'photo.year': 'Godina',
    'photo.author': 'Autor',
    'photo.location': 'Lokacija',
    'photo.story': 'Priča',
    'photo.taggedPeople': 'Označene osobe',
    'photo.comments': 'Komentari',
    'photo.addComment': 'Dodaj komentar',
    
    // Photo tag instructions
    'photo.tag.tip.mobile': '💡 Savjet (mobitel): Dodirni fotografiju da vidiš označene osobe',
    'photo.tag.tip.desktop': '💡 Savjet (računalo): Prijeđi mišem preko fotografije da vidiš označene osobe',
    'photo.tag.pendingInfo': 'Info: Imaš oznake koje čekaju odobrenje administratora. Narančaste točke prikazuju tvoje oznake na čekanju.',


    // Auth
    'auth.signInGoogle': 'Prijavite se s Googleom',
    'auth.signOut': 'Odjava',
    'auth.signInSuccess': 'Uspješno ste se prijavili!',
    'auth.signOutSuccess': 'Uspješno ste se odjavili!',
    'auth.adminLogin': 'Admin prijava',
    'auth.email': 'Email',
    'auth.password': 'Lozinka',
    'auth.adminSignInSuccess': 'Uspješno prijavljen kao administrator!',


'admin.photoApproved': 'Fotografija uspješno odobrena',
'admin.photoRejected': 'Fotografija odbijena i obrisana',
'admin.photoUpdated': 'Fotografija uspješno ažurirana',
'admin.photoDeleted': 'Fotografija uspješno obrisana',
'admin.tagApproved': 'Oznaka uspješno odobrena',
'admin.tagRejected': 'Oznaka odbijena i obrisana',
'admin.tagUpdated': 'Oznaka uspješno ažurirana',
'admin.adminModeExited': 'Uspješno izašli iz admin moda',
'admin.imageUploaded': 'Slika uspješno učitana!',
    
    // Common
    'common.of': 'od',
    'common.save': 'Spremi',
    'common.cancel': 'Odustani',
    'common.edit': 'Uredi',
    'common.delete': 'Obriši',
    'common.loading': 'Učitavanje...',
    'common.error': 'Greška',
    'common.success': 'Uspjeh',
    'common.required': 'Obavezno',
    'common.optional': 'Neobavezno',
    
    // Footer
    'footer.about': 'O nama',
    'footer.contact': 'Kontakt',
    'footer.privacy': 'Pravila privatnosti',
    'footer.terms': 'Uvjeti korištenja',
    'footer.rights': 'Sva prava pridržana',
    'footer.tagline': 'Čuvamo hrvatsku baštinu, jedno sjećanje po jedno.',

    // SearchBar
    'search.placeholder': 'Pretražite grad ili selo...',
    'search.button': 'Pretraži',
    'search.inputPlaceholder': 'Pretražite lokaciju...',
    'search.noLocations': 'Nema pronađenih lokacija',

    // Location stranica
    'location.exploreHistory': 'Istražite povijest kroz fotografije i sjećanja',
    'location.photos': 'fotografija',
    'location.addMemory': 'Dodaj sjećanje',
    'location.signInToAdd': 'Prijavite se za dodavanje',
    'location.searchPlaceholder': 'Pretražite fotografije, opise, autore ili oznake...',
    'location.filters': 'Filtri',
    'location.clear': 'Očisti',
    'location.timePeriod': 'Vremensko razdoblje',
    'location.allYears': 'Sve godine',
    'location.photoType': 'Tip fotografije',
    'location.sortBy': 'Sortiraj po',
    'location.showing': 'Prikazano',
    'location.matching': 'koji odgovaraju',
    'location.from': 'iz',
    'location.in': 'u',
    'location.noPhotosFound': 'Nema pronađenih fotografija',
    'location.tryAdjusting': 'Pokušajte prilagoditi filtre ili pojmove pretrage.',
    'location.beFirst': 'Budite prvi koji će podijeliti povijesnu fotografiju ove lokacije!',
    'location.clearAllFilters': 'Očisti sve filtre',
    'location.loadingMemories': 'Učitavanje sjećanja...',
    'location.loadMoreMemories': 'Učitaj više sjećanja',
    'location.uploadSuccess': 'Fotografija uspješno učitana! Pojavit će se nakon pregleda admina.',
    
    // Photo types
    'photoType.allTypes': 'Svi tipovi',
    'photoType.street': 'Ulični prizori',
    'photoType.building': 'Zgrade', 
    'photoType.people': 'Ljudi',
    'photoType.event': 'Događaji',
    'photoType.nature': 'Priroda',
    
    // Sort options
    'sort.newest': 'Najnovije prvo',
    'sort.oldest': 'Najstarije prvo',
    'sort.popular': 'Najpopularnije',
    'sort.yearNewest': 'Godina (najnovije)',
    'sort.yearOldest': 'Godina (najstarije)',
    
    // PhotoUpload komponenta
    'upload.addPhotoTo': 'Dodaj povijesnu fotografiju u',
    'upload.clickToUpload': 'Kliknite za učitavanje povijesne fotografije',
    'upload.fileTypes': 'PNG, JPG, JPEG do 20MB',
    'upload.specificAddress': 'Specifična adresa u',
    'upload.optional': '(Neobavezno)',
    'upload.searchAddress': 'Pretražite ulicu, znamenitost ili zgradu...',
    'upload.trySearching': 'Pokušajte pretražiti',
    'upload.selectYear': 'Odaberite godinu',
    'upload.whoTookPhoto': 'Tko je snimio ovu fotografiju?',
    'upload.location': 'Lokacija',
    'upload.briefDescription': 'Kratki opis fotografije',
    'upload.detailedStory': 'Detaljna priča (Neobavezno)',
    'upload.shareStory': 'Podijelite priču iza ove fotografije, povijesni kontekst ili osobna sjećanja...',
    'upload.fillRequired': 'Ispunite obavezna polja',
    'upload.shareMemory': 'Podijeli sjećanje',
    'upload.noConnection': 'Nema konekcije',
    'upload.uploading': 'Učitavanje...',
    'upload.photoType': 'Tip fotografije',
'upload.selectPhotoType': 'Odaberite tip fotografije',
 // ✅ Pretraživanje adresa UI
  'upload.searchingAddresses': 'Pretraživanje adresa...',
  'upload.foundAddresses': 'Pronađena {count} adresa',
  'upload.foundAddressesPlural': 'Pronađeno {count} adresa',
  'upload.cached': 'keširano',
  'upload.noAddressesFound': 'Nema pronađenih adresa za',
  'upload.waitingDebounce': 'Čekanje...',
  'upload.cacheEntries': 'Keš: {count} unosa',
  
  // ✅ Ručno pozicioniranje
  'upload.streetFound': '{street} pronađena! Odaberite točnu lokaciju za broj {number}',
  'upload.clickOnMap': 'Kliknite na kartu gdje se točno nalazi ova fotografija',
  'upload.zoomTip': 'Savjet: Uvećajte za veću točnost. Marker će se pojaviti gdje kliknete.',
  
  // ✅ Potvrda lokacije
  'upload.locationSetTitle': 'Lokacija postavljena: {address}',
  'upload.coordinates': 'Koordinate',
  'upload.changeLocation': 'Promijeni',
  'upload.selectedPhotoLocation': 'Odabrana lokacija za fotografiju',
  'upload.locationFoundCoords': 'Lokacija pronađena: {latitude}, {longitude}',

     // Text
    'text.characterCounter': 'znakova',

 
// Croatian translations (hr)
'comments.title': 'Komentari ({count})',
'comments.placeholder': 'Podijelite svoja sjećanja ili znanje o ovoj fotografiji...',
'comments.postComment': 'Objavi komentar',
'comments.signInMessage': 'Prijavite se da podijelite svoja sjećanja i komentare',
'comments.signInToComment': 'Prijavite se za komentiranje',
'comments.signInSuccess': 'Uspješno ste se prijavili! Sada možete komentirati.',
'comments.signInError': 'Neuspjeh pri prijavi. Molimo pokušajte ponovno.',
'comments.commentAdded': 'Vaš komentar je dodan!',
'comments.noComments': 'Još nema komentara. Budite prvi koji će podijeliti svoje misli!',
'comments.author': 'Autor',
'comments.emptyComment': 'Komentar ne može biti prazan',
'comments.mustBeSignedIn': 'Morate biti prijavljeni',
'comments.loadError': 'Greška pri učitavanju komentara',
'comments.postError': 'Greška pri objavljivanju komentara',
'comments.loading': 'Učitavanje komentara...',

// Croatian translations (add to the 'hr' object):
'locationMap.photoLocation': 'Lokacija fotografije',
'locationMap.viewOnMap': 'Pogledaj na karti',
'locationMap.viewPhoto': 'Pogledaj fotografiju',
'locationMap.location': 'Lokacija',
'locationMap.address': 'Adresa',
'locationMap.nearbyPhotos': 'Obližnje fotografije',

// Croatian translations (add to the 'hr' object):
'mapView.memoryMap': 'Karta sjećanja',
'mapView.noPhotos': 'Trenutno nema niti jedne slike',
'mapView.exploreCroatian': 'Istražite hrvatsku baštinu kroz interaktivnu kartu',
'mapView.loadingMemoryMap': 'Učitavanje karte sjećanja...',
'mapView.noLocatedPhotos': 'Još nema lociranih fotografija',
'mapView.photosWillAppear': 'Fotografije će se pojaviti na karti kada budu učitane s određenim adresama.',
'mapView.addPhotosTo': 'Dodaj fotografije u {location}',
'mapView.filters': 'Filtri:',
'mapView.allDecades': 'Sva desetljeća',
'mapView.searchByLocation': 'Pretraži po lokaciji ili adresi...',
'mapView.showing': 'Prikazano {filtered} od {total} fotografija',
'mapView.photosOnMap': 'Fotografije na karti',
'mapView.viewDetails': 'Pogledaj detalje',
'mapView.photosInArea': '{count} fotografija u ovom području',
'mapView.morePhotos': '+{count} fotografija više',
'mapView.locatedPhotos': 'Locirane fotografije',
'mapView.cities': 'Gradovi',
'mapView.specificAddresses': 'Specifične adrese',
'mapView.differentDecades': 'Različita desetljeća',
'mapView.debugInfo': '🔍 Debug informacije:',
'mapView.totalPhotos': 'Ukupno fotografija:',
'mapView.filtered': 'Filtrirano:',
'mapView.currentZoom': 'Trenutni zoom:',
'mapView.clusters': 'Klasteri:',
'mapView.individualMarkers': 'Pojedinačni markeri:',
'mapView.howClusteringWorks': '📍 Kako funkcionira klasteriranje',
'mapView.clusteringDesc1': '• Kada je više fotografija blizu jedna drugoj, grupiraju se u numerirane klastere',
'mapView.clusteringDesc2': '• Kliknite na klaster da vidite sve fotografije u tom području',
'mapView.clusteringDesc3': '• Uvećajte za prikaz pojedinačnih markera fotografija',
'mapView.clusteringDesc4': '• Učitajte više fotografija na istu adresu da vidite klasteriranje u akciji!',

// About page
'about.title': 'O Vremeplovu',
'about.subtitle': 'Čuvamo hrvatsku baštinu, jedno sjećanje po jedno',
'about.ourMission': 'Naša misija',
'about.missionText1': 'Vremeplov.hr je digitalna platforma posvećena čuvanju i dijeljenju bogate vizualne povijesti hrvatskih gradova i sela. Vjerujemo da svaka fotografija priča priču i da svaka priča zaslužuje biti sačuvana za buduće generacije.',
'about.missionText2': 'Naša misija je stvoriti sveobuhvatan arhiv povijesnih fotografija iz cijele Hrvatske, učiniti ova dragocjena sjećanja dostupnima svima te potaknuti dublju povezanost s našom baštinom.',
'about.howWeHelp': 'Kako pomagamo zajednicama',
'about.digitalPreservation': 'Digitalno očuvanje',
'about.digitalPreservationDesc': 'Pružamo siguran digitalni dom za povijesne fotografije koje bi inače mogle biti izgubljene u vremenu.',
'about.localHistory': 'Dokumentiranje lokalne povijesti',
'about.localHistoryDesc': 'Svaka lokacija dobiva svoj vlastiti prostor, stvarajući sveobuhvatne vizualne povijesti hrvatskih mjesta.',
'about.communityConnection': 'Povezivanje zajednice',
'about.communityConnectionDesc': 'Ljudi mogu označiti rodbinu, podijeliti priče i povezati se s drugima koji dijele njihovu baštinu.',
'about.culturalHeritage': 'Kulturna baština',
'about.culturalHeritageDesc': 'Pomagamo zajednicama održati njihov kulturni identitet čuvanjem vizualnih sjećanja.',
'about.aboutDeveloper': 'O developeru',
'about.developerText1': 'Vremeplov.hr je stvorio Kruno Žagar, strastveni developer posvećen čuvanju hrvatske baštine kroz tehnologiju. Razumijevajući važnost naše kulturne povijesti i opasnost gubitka dragocjenih sjećanja, Kruno je razvio ovu platformu kako bi osigurao da buduće generacije mogu istraživati i povezivati se sa svojim korijenima.',
'about.developerText2': 'Ovaj projekt predstavlja osobnu predanost vraćanju zajednici pružanjem vrijedne usluge koja pomaže u čuvanju naše zajedničke kulturne baštine.',
'about.getInvolved': 'Uključite se',
'about.getInvolvedText': 'Pomozite nam izgraditi najsveobuhvatniji arhiv hrvatskih povijesnih fotografija. Vaši doprinosi čine razliku u čuvanju naše baštine.',
'about.startContributing': 'Počnite doprinositi',

// Privacy page
'privacy.title': 'Pravila privatnosti',
'privacy.subtitle': 'Kako štitimo i rukujemo vašim podacima',
'privacy.dataCollection': 'Prikupljanje i čuvanje podataka',
'privacy.dataCollectionText1': 'Kad učitate fotografije na Vremeplov.hr, prikupljamo i čuvamo sljedeće informacije:',
'privacy.dataCollectionList1': 'Povijesne fotografije koje odaberete podijeliti',
'privacy.dataCollectionList2': 'Metapodatke fotografija (godina, lokacija, opis, autor)',
'privacy.dataCollectionList3': 'Komentare i oznake koje dodate fotografijama',
'privacy.dataCollectionList4': 'Osnovnu analitiku korištenja za poboljšanje platforme',
'privacy.dataCollectionText2': 'Sve učitane fotografije se sigurno čuvaju u našoj bazi podataka i javno su dostupne na platformi kako bi ispunile našu misiju čuvanja hrvatske baštine. Učitavanjem sadržaja, dajete dozvolu za prikazivanje na Vremeplov.hr.',
'privacy.dataProtection': 'Zaštita podataka',
'privacy.dataProtectionText1': 'Ozbiljno shvaćamo sigurnost vaših podataka. Sva učitavanja se obrađuju kroz sigurne veze i čuvaju koristeći standardne sigurnosne mjere industrije.',
'privacy.dataProtectionText2': 'Ne prodajemo, mijenjamo ili prenošamo vaše osobne informacije trećim stranama. Vaši podaci se koriste isključivo za rad i poboljšanje Vremeplov.hr.',
'privacy.contentRemoval': 'Uklanjanje sadržaja',
'privacy.contentRemovalText1': 'Ako trebate ukloniti fotografije ili drugi sadržaj koji ste učitali, možete zatražiti brisanje kontaktirajući nas s valjanim razlogom. Revizirat ćemo svaki zahtjev i ukloniti sadržaj kad je to prikladno.',
'privacy.contentRemovalText2': 'Valjani razlozi za uklanjanje sadržaja uključuju:',
'privacy.contentRemovalList1': 'Zabrinutosti oko autorskih prava ili sporovi o vlasništvu',
'privacy.contentRemovalList2': 'Zabrinutosti oko privatnosti osoba na fotografijama',
'privacy.contentRemovalList3': 'Netočne ili obmanjujuće informacije',
'privacy.contentRemovalList4': 'Osobni ili obiteljski zahtjevi za uklanjanjem',
'privacy.privacyQuestions': 'Pitanja o privatnosti',
'privacy.privacyQuestionsText': 'Ako imate pitanja o ovim pravilima privatnosti ili zabrinutosti oko svojih podataka, molimo kontaktirajte nas na:',
'privacy.policyUpdates': 'Ažuriranja pravila',
'privacy.policyUpdatesText': 'Ova pravila privatnosti mogu se povremeno ažurirati. Sve promjene bit će objavljene na ovoj stranici s ažuriranim datumom revizije. Nastavak korištenja Vremeplov.hr nakon promjena predstavlja prihvaćanje ažuriranih pravila.',
'privacy.lastUpdated': 'Zadnje ažurirano: {date}',
'privacy.gdprRights': 'Vaša prava prema GDPR-u',
'privacy.gdprRightsText': 'Prema GDPR-u, imate sljedeća prava:',
'privacy.rightAccess': 'Pravo na pristup vašim osobnim podacima',
'privacy.rightDelete': 'Pravo na brisanje vašeg računa i svih povezanih podataka',
'privacy.rightExport': 'Pravo na izvoz svih vaših podataka',
'privacy.rightCorrect': 'Pravo na ispravak netočnih podataka',
'privacy.rightsContact': 'Za ostvarivanje ovih prava, molimo kontaktirajte nas na:',
'privacy.thirdPartyServices': 'Servisi trećih strana',
'privacy.thirdPartyText': 'Koristimo sljedeće servise trećih strana:',
'privacy.firebaseDesc': 'Hosting podataka (Lokacija servera: EU - Belgija i Nizozemska)',
'privacy.analyticsDesc': 'Analitika web stranice',
'privacy.mapsDesc': 'Prikaz lokacija na karti',
'privacy.thirdPartyNote': 'Svaki servis ima vlastitu politiku privatnosti. Ne dijelimo vaše podatke s trećim stranama osim za navedene servise.',
'privacy.dataRetention': 'Razdoblje čuvanja podataka',
'privacy.dataRetentionText': 'Podatke čuvamo sljedeća razdoblja:',
'privacy.retentionApproved': 'Odobrene fotografije: Trajno (dok god platforma postoji)',
'privacy.retentionAccount': 'Podaci o korisničkom računu: Dok god je račun aktivan',
'privacy.retentionUnapproved': 'Neodobrene fotografije: Automatski se brišu nakon 90 dana',

// Terms page
'terms.title': 'Uvjeti korištenja',
'terms.subtitle': 'Pravila i smjernice za korištenje Vremeplov.hr',
'terms.acceptance': 'Prihvaćanje uvjeta',
'terms.acceptanceText': 'Pristupanjem i korištenjem Vremeplov.hr, prihvaćate i slažete se biti vezani ovim uvjetima i odredbama. Ako se ne slažete s ovim uvjetima, molimo ne koristite našu platformu.',
'terms.contentCopyright': 'Sadržaj i autorska prava',
'terms.contentText1': 'Kada učitavate sadržaj na Vremeplov.hr, morate osigurati da:',
'terms.contentList1': 'Posjedujete prava na fotografije ili imate dozvolu za njihovo dijeljenje',
'terms.contentList2': 'Sadržaj je povijesno točan prema vašem najboljem znanju',
'terms.contentList3': 'Fotografije su prikladne i poštuju sve prikazane osobe',
'terms.contentList4': 'Sadržaj ne krši prava treće strane ili važeće zakone',
'terms.contentText2': 'Učitavanjem sadržaja, dajete Vremeplov.hr neekskluzivnu licencu za prikazivanje, čuvanje i dijeljenje vaših doprinosa kao dijela naše misije očuvanja kulturne baštine.',
'terms.userResponsibilities': 'Odgovornosti korisnika',
'terms.userText1': 'Kao korisnik Vremeplov.hr, slažete se da ćete:',
'terms.userList1': 'Pružiti točne informacije kad učitavate fotografije i metapodatke',
'terms.userList2': 'Koristiti platformu s poštovanjem i ne sudjelovati u uznemiravanje ili neprikladno ponašanje',
'terms.userList3': 'Poštovati privatnost i dostojanstvo osoba na povijesnim fotografijama',
'terms.userList4': 'Prijaviti sadržaj koji krši ove uvjete ili se čini neprikladan',
'terms.userList5': 'Ne pokušavati oštetiti, onemogućiti ili narušiti funkcionalnost platforme',
'terms.moderation': 'Moderacija sadržaja',
'terms.moderationText': 'Zadržavamo pravo pregledati i ukloniti sadržaj koji:',
'terms.moderationList1': 'Krši autorska prava ili prava intelektualnog vlasništva',
'terms.moderationList2': 'Sadrži neprikladan ili uvredljiv materijal',
'terms.moderationList3': 'Nije relevantan za hrvatsku povijesnu dokumentaciju',
'terms.moderationList4': 'Uključuje osobne podatke trećih osoba bez pristanka',
'terms.moderationWarning': 'Ponovljeno kršenje ovih smjernica može rezultirati trajnom suspenzijom računa.',
'terms.copyrightLiability': 'Vremeplov.hr ne preuzima odgovornost za pitanja autorskih prava vezana uz uploadane slike. Korisnici su isključivo odgovorni za osiguravanje prava korištenja i dijeljenja sadržaja koji učitavaju.',
'terms.prohibited': 'Zabranjene aktivnosti',
'terms.prohibitedText': 'Sljedeće aktivnosti su strogo zabranjene na Vremeplov.hr:',
'terms.prohibitedList1': 'Učitavanje materijala zaštićenog autorskim pravima bez dozvole',
'terms.prohibitedList2': 'Dijeljenje lažnih ili obmanjujućih povijesnih informacija',
'terms.prohibitedList3': 'Učitavanje neprikladnog, uvredljivog ili štetnog sadržaja',
'terms.prohibitedList4': 'Pokušaji hakiranje, špam ili drugo zlouporaba platforme',
'terms.prohibitedList5': 'Komercijalna upotreba bez eksplicitne dozvole',
'terms.availability': 'Dostupnost platforme',
'terms.availabilityText': 'Iako nastojimo održati dostupnost 24/7, Vremeplov.hr može povremeno biti nedostupan zbog održavanja, ažuriranja ili tehničkih problema. Nismo odgovorni za neugodnosti uzrokovane privremenom nedostupnošću.',
'terms.liability': 'Ograničenje odgovornosti',
'terms.liabilityText': 'Vremeplov.hr se pruža "kao što jest" bez ikakvih jamstava. Nismo odgovorni za štete nastale vašim korištenjem platforme, uključujući ali ne ograničavajući se na gubitak podataka, prekide usluge ili netočnosti u sadržaju korisnika.',
'terms.questionsAbout': 'Pitanja o uvjetima',
'terms.questionsText': 'Ako imate pitanja o ovim uvjetima korištenja, molimo kontaktirajte nas na',
'terms.termsUpdates': 'Ažuriranja uvjeta',
'terms.termsUpdatesText': 'Ovi uvjeti se mogu povremeno ažurirati. Promjene će biti objavljene na ovoj stranici. Nastavak korištenja platforme nakon promjena predstavlja prihvaćanje ažuriranih uvjeta.',

// Contact page
'contact.title': 'Kontakt',
'contact.subtitle': 'Stupite u kontakt s Vremeplov.hr timom',
'contact.getInTouch': 'Stupite u kontakt',
'contact.getInTouchText': 'Volio bismo čuti od vas! Bilo da imate pitanja, prijedloge ili trebate pomoć, tu smo da vam pomognemo.',
'contact.ourEmail': 'Naš e-mail za sve Vremeplov.hr upite',
'contact.whatCanWeHelp': 'S čime vam možemo pomoći?',
'contact.technicalSupport': 'Tehnička podrška',
'contact.techList1': '• Problemi s učitavanjem fotografija',
'contact.techList2': '• Problemi s funkcionalnosti web stranice',
'contact.techList3': '• Pomoć s računom ili prijavom',
'contact.techList4': '• Problemi s mobilnom kompatibilnosti',
'contact.contentManagement': 'Upravljanje sadržajem',
'contact.contentList1': '• Zahtjev za uklanjanje fotografija',
'contact.contentList2': '• Prijaviti neprikladan sadržaj',
'contact.contentList3': '• Ispraviti informacije o fotografiji',
'contact.contentList4': '• Zabrinutosti oko autorskih prava',
'contact.partnership': 'Partnerstvo i suradnja',
'contact.partnershipList1': '• Partnerstva s muzejima',
'contact.partnershipList2': '• Suradnje sa zajednicom',
'contact.partnershipList3': '• Projekti obrazovnih institucija',
'contact.partnershipList4': '• Upiti medija i tiska',
'contact.generalFeedback': 'Općenite povratne informacije',
'contact.feedbackList1': '• Prijedlozi za poboljšanje',
'contact.feedbackList2': '• Zahtjevi za novim funkcijama',
'contact.feedbackList3': '• Podijelite svoju priču',
'contact.feedbackList4': '• Općenita pitanja o projektu',
'contact.responseTime': 'Vrijeme odgovora',
'contact.responseTimeText': 'Tipično odgovaramo na sve upite unutar 24-48 sati. Za hitne slučajeve, molimo označite svoj e-mail kao "HITNO" u predmetu. Cijenimo vašu strpljivost i radujemo se što vam možemo pomoći doprinijeti čuvanju hrvatske baštine.',
'contact.otherWays': 'Drugi načini povezivanja',
'contact.otherWaysText': 'Iako je e-mail naš primarni način kontakta, možete nas kontaktirati i putem naših kanala društvenih mreža ili foruma zajednice kada postanu dostupni.',
'contact.newsletter': 'Pratite naš razvoj i ažuriranja pretplaćivanjem na naš bilten (uskoro)',

// FAQ stranica
'faq.title': 'Često postavljana pitanja',
'faq.subtitle': 'Pronađite odgovore na najčešća pitanja o Vremeplov.hr',
'faq.uploadModeration': 'Upload i moderacija',
'faq.q1': 'Zašto mogu uploadati samo 1 sliku dnevno?',
'faq.a1': 'Novi korisnici imaju limit od 1 slike dnevno. Nakon što admin odobri 5 fotografija, automatski dobivaš Verified status (3 slike/dan). Nastavi doprinositi da otključaš više razine: Contributor (5/dan) i Power User (10/dan).',
'faq.q2': 'Zašto moja slika još nije objavljena?',
'faq.a2': 'Sve slike prolaze kroz ručnu moderaciju kako bi osigurali kvalitetu arhiva. Obično odobravamo slike unutar 24-48 sati. Primit ćeš notifikaciju kad slika bude odobrena.',
'faq.q3': 'Što ako admin odbije moju sliku?',
'faq.a3': 'Razlozi mogu biti: loša kvaliteta, nije relevantno za Hrvatsku, zaštićen materijal autorskim pravima, ili nedostaju informacije. Možeš ponovno uploadati s ispravkama.',
'faq.copyrightOwnership': 'Autorska prava i vlasništvo',
'faq.q4': 'Mogu li uploadati stare slike iz obiteljskog albuma?',
'faq.a4': 'DA, ako si vlasnik slika ili imaš dopuštenje vlasnika. Nemoj uploadati slike s interneta ili tuđih izvora bez dopuštenja.',
'faq.q5': 'Što ako netko uploada moju sliku bez dopuštenja?',
'faq.a5': 'Kontaktiraj nas na vremeplov.app@gmail.com s "HITNO" u predmetu i odmah ćemo ukloniti sliku.',
'faq.locationAddress': 'Lokacija i adrese',
'faq.q6': 'Moram li dodati adresu pri uploadu?',
'faq.a6': 'NE, adresa je opcionalna. Ali ako dodaš točnu adresu, tvoja slika će biti vidljiva na Memory Map karti.',
'faq.q7': 'Ne mogu pronaći svoju ulicu u pretraživanju, što sad?',
'faq.a7': 'Probaj širu pretragu (npr. samo naziv grada), ili uploadaj bez adrese. Možeš dodati adresu u opis slike.',
'faq.accountTiers': 'Korisnički račun i razine',
'faq.q8': 'Kako mogu povećati svoj dnevni limit?',
'faq.a8': 'Sustav razina: NEW_USER (1/dan) → Uploadaj 5 odobrenih slika → VERIFIED (3/dan) → Uploadaj 15 odobrenih slika → CONTRIBUTOR (5/dan) → Uploadaj 30 odobrenih slika → POWER_USER (10/dan)',
'faq.q9': 'Zašto trebam Google račun?',
'faq.a9': 'Google Sign-In omogućava brzu i sigurnu prijavu bez dodatnih lozinki. Ne dijelimo tvoje podatke s trećim stranama.',
'faq.privacyData': 'Privatnost i podaci',
'faq.q10': 'Mogu li obrisati svoj račun i sve slike?',
'faq.a10': 'DA. Kontaktiraj nas putem emaila i obradit ćemo tvoj GDPR zahtjev unutar 30 dana. Sve tvoje slike i podaci bit će trajno obrisani.',
'faq.q11': 'Gdje se čuvaju moje slike?',
'faq.a11': 'Sigurno na Google Firebase serverima u EU regiji (Belgija/Nizozemska), u skladu s GDPR-om.',
'faq.technical': 'Tehnički problemi',
'faq.q12': 'Web stranica je spora ili ne radi, što da radim?',
'faq.a12': 'Pokušaj osvježiti stranicu, obrisati cache u browseru, ili koristiti drugi browser. Ako problem i dalje postoji, kontaktiraj nas na vremeplov.app@gmail.com.',
'faq.stillHaveQuestions': 'Još uvijek imaš pitanja?',
'faq.contactUs': 'Kontaktiraj nas na',
'faq.andWeWillHelp': 'i rado ćemo ti pomoći!',

// Croatian translations  
// Profile page
'profile.achievements': 'Postignuća',
'profile.followers': 'Pratitelji',
'profile.following': 'Pratim',
'profile.photos': 'Fotografije',
'profile.statistics': 'Statistike',
'profile.activity': 'Nedavna aktivnost',
'profile.editProfile': 'Uredi profil',
'profile.follow': 'Prati',
'profile.displayName': 'Ime za prikaz',
'profile.bio': 'Biografija',
'profile.joined': 'Pridružio se',
'profile.displayNamePlaceholder': 'Vaše ime za prikaz',
'profile.tellAboutYourself': 'Recite nam nešto o sebi...',
'profile.yourLocation': 'npr. Zagreb, Hrvatska',
'profile.saveChanges': 'Spremi promjene',
'profile.cancel': 'Odustani',
'profile.contributionStats': 'Statistike doprinosa',
'profile.totalPhotos': 'Ukupno fotografija',
'profile.uniqueLocations': 'Jedinstvene lokacije',
'profile.totalLikesReceived': 'Ukupno primljenih sviđanja',
'profile.totalViews': 'Ukupno pogleda',
'profile.achievementsEarned': 'Osvojena postignuća',
'profile.communityImpact': 'Utjecaj na zajednicu',
'profile.avgLikesPerPhoto': 'Prosjek sviđanja po fotografiji',
'profile.avgViewsPerPhoto': 'Prosjek pogleda po fotografiji',
'profile.memberSince': 'Član od',
'profile.noPhotosYet': 'Još nema fotografija',
'profile.startSharing': 'Počnite dijeliti svoje povijesne fotografije i izgradite svoju kolekciju!',
'profile.userHasntShared': 'Ovaj korisnik još nije podijelio fotografije.',
'profile.uploadFirstPhoto': 'Učitajte svoju prvu fotografiju',
'profile.noRecentActivity': 'Nema nedavnih aktivnosti',
'profile.startUploading': 'Počnite učitavati fotografije i komunicirajte sa zajednicom da vidite svoju aktivnost ovdje!',
'profile.collectionOverview': 'Pregled kolekcije',
'profile.totalLikes': 'Ukupno sviđanja',
'profile.locations': 'Lokacije',
'profile.unknown': 'Nepoznato',
'profile.loadingProfile': 'Učitavanje profila...',
'profile.loadError': 'Neuspjeh pri učitavanju profila',
'profile.unfollowed': 'Prestali ste pratiti korisnika',
'profile.nowFollowing': 'Sada pratite korisnika!',
'profile.followError': 'Neuspjeh pri ažuriranju praćenja',
'profile.updateSuccess': 'Profil je uspješno ažuriran!',
'profile.updateError': 'Neuspjeh pri ažuriranju profila',
'profile.statsFixed': 'Statistike korisnika uspješno popravljena!',
'profile.statsError': 'Neuspjeh pri popravljanju statistika',
'profile.defaultBio': 'Strastveno čuvam hrvatsku baštinu kroz povijesnu fotografiju.',
'profile.editProfileDescription': 'Ažurirajte svoje informacije o profilu.',
'profile.loadMore': 'Učitaj više aktivnosti',
'profile.loading': 'Učitavanje...',
'profile.loadMoreError': 'Greška pri učitavanju aktivnosti',
'profile.loadMorePhotos': 'Učitaj više slika',
'profile.photosLoaded': 'Učitane slike',


// Badge names
'profile.badgePhotographer': 'Fotograf',
'profile.badgeHistorian': 'Lokalni povjesničar',
'profile.badgeExplorer': 'Istraživač baštine',
'profile.badgePopular': 'Favorit zajednice',
'profile.badgeSocial': 'Društveni leptir',
'profile.badgeVeteran': 'Veteran baštine',
'profile.badgeLegend': 'Legenda baštine',

// Activity translations
'profile.activityUploaded': 'učitao/la je fotografiju',
'profile.activityLiked': 'se svidjela fotografija',
'profile.activityFollowed': 'počeo/la je pratiti',
'profile.activityBadge': 'osvojio/la je značku',
'profile.activityComment': 'dodao/la je komentar',
'profile.activityTagged': 'označio/la je osobu u',

//Community

// Croatian translations
// Community page
'community.leaderboard': 'Zajednica - Ljestvica',
'community.celebratingContributors': 'Slavimo naše najbolje doprinose baštini',
'community.timePeriod': 'Vremensko razdoblje',
'community.allTime': 'Sve vrijeme',
'community.thisYear': 'Ova godina',
'community.thisMonth': 'Ovaj mjesec',
'community.updatedDaily': 'Ažurirano dnevno u ponoć',
'community.mostPhotos': 'Najviše fotografija',
'community.mostLiked': 'Najviše sviđanja',
'community.mostLocations': 'Najviše lokacija',
'community.newMembers': 'Novi članovi',
'community.places': 'Mjesta',
'community.new': 'Novo',
'community.likes': 'Omiljeno',
'community.locations': 'lokacije',
'community.joined': 'pridružio se',
'community.badge': 'značka',
'community.loadingLeaderboard': 'Učitavanje ljestvice...',
'community.topContributorsByPhotos': 'Najbolji doprinositelji po fotografijama',
'community.mostAppreciatedContributors': 'Najcjenjeniji doprinositelji',
'community.heritageExplorers': 'Istraživači baštine',
'community.welcomeNewMembers': 'Dobrodošli novi članovi',
'community.communityStats': 'Statistike zajednice',
'community.totalMembers': 'Ukupno članova',
'community.photosShared': 'Podijeljene fotografije',
'community.locationsDocumented': 'Dokumentirane lokacije',
'community.thisMonthsHighlights': 'Istaknuto ovaj mjesec',
'community.mostActiveLocation': 'Najaktivnija lokacija',
'community.newPhotos': 'nove fotografije',
'community.photoOfTheMonth': 'Fotografija mjeseca',
'community.by': 'od',
'community.fromLastMonth': 'od prošlog mjeseca',
'community.achievementSystem': 'Sustav postignuća',
'community.earnBadges': 'Osvajajte značke doprinosom našoj kolekciji baštine:',
'community.photographer': 'Fotograf: Učitajte svoju prvu fotografiju',
'community.localHistorian': 'Lokalni povjesničar: Podijelite 10+ fotografija',
'community.heritageExplorer': 'Istraživač baštine: 5+ lokacija',
'community.communityFavorite': 'Favorit zajednice: 100+ sviđanja',

'userProfile.myProfile': 'Moj profil',
'userProfile.community': 'Zajednica',
'userProfile.signOut': 'Odjava',

// ✅ ERROR MESSAGES - CROATIAN
    'errors.signInFailed': 'Prijava nije uspjela',
    'errors.signOutFailed': 'Odjava nije uspjela',
    'errors.signInRequired': 'Molimo prijavite se da biste lajkali fotografije',
    'errors.adminModeExit': 'Greška pri izlasku iz admin moda',
    'errors.adminModeEnter': 'Greška pri ulasku u admin mod',
    
    // Upload errors
    'errors.fillAllFields': 'Molimo ispunite sva polja i odaberite sliku',
    'errors.invalidImageType': 'Molimo odaberite valjanu sliku (JPG, PNG, WEBP)',
    'errors.imageTooLarge': 'Slika je prevelika (max 20MB). Molimo komprimirajte sliku',
    'errors.uploadFailed': 'Upload nije uspio: Greška s dopuštenjima ili kvota premašena',
    'errors.uploadError': 'Upload nije uspio: Loša internet veza ili problem sa serverom',
    'errors.compressionError': 'Greška pri kompresiji slike',
    'errors.addressSearchFailed': 'Pretraživanje adresa nije uspjelo',
    'errors.fileRequired': 'Molimo odaberite datoteku',
    'errors.offline': 'Niste povezani na internet. Molimo provjerite vezu',
    
    // Photo errors
    'errors.photoLoadFailed': 'Učitavanje fotografija nije uspjelo',
    'errors.photoLikeFailed': 'Lajkanje fotografije nije uspjelo',
    'errors.photoDeleteFailed': 'Brisanje fotografije nije uspjelo',
    'errors.photoUpdateFailed': 'Ažuriranje fotografije nije uspjelo',
    'errors.photoApprovalFailed': 'Odobravanje fotografije nije uspjelo',
    'errors.photoTagApprovalFailed': 'Odobravanje oznake nije uspjelo',
    'errors.photoTagRejectionFailed': 'Odbijanje oznake nije uspjelo',
    'errors.photoTagUpdateFailed': 'Ažuriranje oznake nije uspjelo',
    'errors.photoNotFound': 'Fotografija nije pronađena',
    'errors.photoAddFailed': 'Dodavanje fotografije nije uspjelo',
    
    // Comment errors
    'errors.commentError': 'Greška pri objavi komentara',
    'errors.commentEmpty': 'Komentar ne može biti prazan',
    'errors.commentSignInRequired': 'Molimo prijavite se da biste komentirali',
    'errors.commentLoadFailed': 'Učitavanje komentara nije uspjelo',
    
    // Location errors
    'errors.locationLoadFailed': 'Učitavanje lokacije nije uspjelo',
    
    // Admin errors
    'errors.adminDataLoadFailed': 'Učitavanje admin podataka nije uspjelo',
    
    // Profile errors
    'errors.profileLoadError': 'Učitavanje profila nije uspjelo',
    'errors.followError': 'Greška pri praćenju korisnika',
    'errors.updateError': 'Ažuriranje profila nije uspjelo',
    'errors.statsError': 'Učitavanje statistike nije uspjelo',
    
    // Community errors
    'errors.loadFailed': 'Učitavanje podataka nije uspjelo',
    'errors.leaderboardLoadFailed': 'Učitavanje ljestvice nije uspjelo',
    
    // Photo details errors
    'errors.notFound': 'Fotografija nije pronađena',
    'errors.enterNameAndPosition': 'Molimo unesite ime i odaberite poziciju',
    'errors.tagSaveFailed': 'Spremanje oznake nije uspjelo',
    'errors.signInMessage': 'Molimo prijavite se da biste dodali oznake',
    'errors.likeFailed': 'Lajkanje fotografije nije uspjelo',
    'errors.signInToLike': 'Molimo prijavite se da biste lajkali fotografije',
    
    // Auth errors
    'errors.signInError': 'Greška pri prijavi. Molimo pokušajte ponovno.',
    'errors.signInToAddMemory': 'Molimo prijavite se za dodavanje sjećanja',

  }
};

// Helper function for string interpolation
export const translateWithParams = (t: (key: string) => string, key: string, params: Record<string, string | number>) => {
  let translation = t(key);
  Object.entries(params).forEach(([param, value]) => {
    translation = translation.replace(new RegExp(`{${param}}`, 'g'), String(value));
  });
  return translation;
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Check localStorage first, then browser language, fallback to English
    const saved = localStorage.getItem('language') as Language;
    if (saved) return saved;
    
    const browserLang = navigator.language.toLowerCase();
    return browserLang.startsWith('hr') ? 'hr' : 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const value = {
    language,
    setLanguage,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};