import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'hr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

// Translation object
type TranslationMap = { [key: string]: string };

const translations: Record<Language, TranslationMap> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.dashboard': 'Dashboard',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    'nav.admin': 'Admin',
    'nav.memoryMap': 'Memory Map',
    
    // Home page
    'home.title': 'Croatian Historical Photos',
    'home.subtitle': 'Preserve and share Croatia\'s rich photographic heritage',
    'home.description': 'Discover historical photographs from across Croatia. Share your own family photos and help preserve our cultural memory for future generations.',
    'home.upload': 'Upload Photo',
    'home.explore': 'Explore Gallery',
    'home.recent': 'Recent Photos',
    'home.reconnectTitle': 'Reconnect with Your Heritage',
    'home.discoverTitle': 'Discover Places',
    'home.discoverDesc': 'Search for any city or village in Croatia and explore its visual history on our interactive map.',
    'home.preserveTitle': 'Preserve Memories',
    'home.preserveDesc': 'Upload and share historical photos and videos from your family archives.',
    'home.connectTitle': 'Connect People',
    'home.connectDesc': 'Tag individuals, share stories, and reconnect with your community.',
    'home.exploreCroatiaTitle': 'Explore Croatia Through Time',
    'home.exploreCroatiaDesc': 'Discover historical photos geographically and see how your favorite places looked throughout history.',
    'home.exploreMemoryMap': 'Explore Memory Map',
    'home.glimpseTitle': 'Glimpse into the Past',
    'home.glimpseDesc': 'Browse through our collection of historical photos from various Croatian locations.',
    'home.startJourneyTitle': 'Start Your Journey Through Time',
    'home.startJourneyDesc': 'Join our community and help preserve the visual history of Croatia for future generations.',
    
    // Photo Detail Page
    'photoDetail.loading': 'Loading memory...',
    'photoDetail.notFound': 'Photo not found',
    'photoDetail.notFoundDesc': 'The requested memory could not be found.',
    'photoDetail.returnHome': 'Return to Homepage',
    'photoDetail.aboutPhoto': 'About this photo',
    'photoDetail.year': 'Year',
    'photoDetail.author': 'Author',
    'photoDetail.location': 'Location',
    'photoDetail.uploadedBy': 'Uploaded by',
    'photoDetail.on': 'on',
    'photoDetail.taggedPeople': 'Tagged People',
    'photoDetail.historicalContext': 'Historical Context',
    'photoDetail.relatedPhotos': 'Related Photos',
    'photoDetail.morePhotosFrom': 'More Photos from',
    'photoDetail.views': 'views',
    'photoDetail.likes': 'likes',
    'photoDetail.likePhoto': 'Like Photo',
    'photoDetail.unlikePhoto': 'Unlike Photo',
    'photoDetail.signInToLike': 'Sign In to Like',
    'photoDetail.signInMessage': 'Please sign in to like photos and interact with memories',
    'photoDetail.tagPerson': 'Tag Person',
    'photoDetail.clickToPosition': 'Click on the photo to position the tag',
    'photoDetail.personName': 'Person\'s name',
    'photoDetail.saveTag': 'Save Tag',
    'photoDetail.cancel': 'Cancel',
    'photoDetail.positionSelected': 'Position selected. Please enter a name for the tag.',
    'photoDetail.enterNameAndPosition': 'Please enter a name and select a position on the image',
    'photoDetail.taggedSuccess': 'Person tagged successfully!',
    'photoDetail.tagSaveFailed': 'Failed to add tag',
    'photoDetail.commentAdded': 'Comment added successfully!',
    'photoDetail.commentFailed': 'Failed to add comment',
    'photoDetail.photoLiked': 'Photo liked!',
    'photoDetail.photoUnliked': 'Photo unliked!',
    'photoDetail.likeFailed': 'Failed to update like',
    'photoDetail.historicalContextDesc': 'This period marked significant developments in the local history of {location}. Many similar photographs from this era document the changing landscape and daily life of inhabitants.',
    'photoDetail.defaultDescription': 'This historical photograph from {year} shows {description} in {location}. It was contributed to the Vremeplov.hr archive by {author}.',
    
    // Upload
    'upload.title': 'Share Historical Photo',
    'upload.select': 'Select Photo',
    'upload.drag': 'Drag and drop your photo here, or click to select',
    'upload.year': 'Year',
    'upload.author': 'Author/Photographer',
    'upload.description': 'Short Description',
    'upload.story': 'Detailed Story',
    'upload.submit': 'Upload Photo',
    'upload.cancel': 'Cancel',
    'upload.success': 'Photo uploaded successfully!',
    'upload.error': 'Failed to upload photo',
    'upload.offline': 'You are offline',
    'upload.tagPerson': 'Tag Person',
    'upload.enterName': 'Enter person\'s name',
    'upload.saveTag': 'Save Tag',
    'upload.cancelTag': 'Cancel',
    
    // Gallery
    'gallery.noPhotos': 'No photos yet',
    'gallery.noPhotosDesc': 'Be the first to share a historical photo and help preserve Croatian heritage!',
    'gallery.loading': 'Loading photos...',
    
    // Photo detail
    'photo.year': 'Year',
    'photo.author': 'Author',
    'photo.location': 'Location',
    'photo.story': 'Story',
    'photo.taggedPeople': 'Tagged People',
    'photo.comments': 'Comments',
    'photo.addComment': 'Add Comment',
    
    // Auth
    'auth.signInGoogle': 'Sign in with Google',
    'auth.signOut': 'Sign Out',
    'auth.signInSuccess': 'Successfully signed in!',
    'auth.signOutSuccess': 'Successfully signed out!',
    'auth.adminLogin': 'Admin Login',
    'auth.email': 'Email',
    'auth.password': 'Password',
    
    // Common
    'common.of': 'of',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.required': 'Required',
    'common.optional': 'Optional',
    
    // Footer
    'footer.about': 'About',
    'footer.contact': 'Contact',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.rights': 'All rights reserved',
    'footer.tagline': 'Preserving Croatian heritage, one memory at a time.',

     // SearchBar
    'search.placeholder': 'Search for a city or village...',
    'search.button': 'Search',
    'search.inputPlaceholder': 'Search location...',
    'search.noLocations': 'No locations found',

    // Location stranica
    'location.exploreHistory': 'Explore the history of',
    'location.throughPhotos': 'through photos and memories',
    'location.photos': 'photos',
    'location.addMemory': 'Add Memory',
    'location.signInToAdd': 'Sign In to Add Memory',
    'location.searchPlaceholder': 'Search photos, descriptions, authors, or tags...',
    'location.filters': 'Filters',
    'location.clear': 'Clear',
    'location.timePeriod': 'Time Period',
    'location.allYears': 'All years',
    'location.photoType': 'Photo Type',
    'location.sortBy': 'Sort By',
    'location.showing': 'Showing',
    'location.matching': 'matching',
    'location.from': 'from',
    'location.in': 'in',
    'location.noPhotosFound': 'No photos found',
    'location.tryAdjusting': 'Try adjusting your filters or search terms.',
    'location.beFirst': 'Be the first to share a historical photo of this location!',
    'location.clearAllFilters': 'Clear all filters',
    'location.loadingMemories': 'Loading memories...',
    'location.loadMoreMemories': 'Load More Memories',

    // Photo types
    'photoType.allTypes': 'All Types',
    'photoType.street': 'Street Scenes', 
    'photoType.building': 'Buildings',
    'photoType.people': 'People',
    'photoType.event': 'Events',
    'photoType.nature': 'Nature',
    
    // Sort options
    'sort.newest': 'Newest First',
    'sort.oldest': 'Oldest First',
    'sort.popular': 'Most Popular',
    'sort.yearNewest': 'Year (Newest)',
    'sort.yearOldest': 'Year (Oldest)',
    
    // PhotoUpload komponenta
    'upload.addPhotoTo': 'Add Historical Photo to',
    'upload.clickToUpload': 'Click to upload a historical photo',
    'upload.fileTypes': 'PNG, JPG, JPEG up to 5MB',
    'upload.specificAddress': 'Specific Address in',
    'upload.optional': '(Optional)',
    'upload.searchAddress': 'Search for street, landmark, or building...',
    'upload.trySearching': 'Try searching',
    'upload.selectYear': 'Select year',
    'upload.whoTookPhoto': 'Who took this photo?',
    'upload.location': 'Location',
    'upload.briefDescription': 'Brief description of the photo',
    'upload.detailedStory': 'Detailed Story (Optional)',
    'upload.shareStory': 'Share the story behind this photo, historical context, or personal memories...',
    'upload.fillRequired': 'Fill Required Fields',
    'upload.shareMemory': 'Share Memory',
    'upload.noConnection': 'No Connection',
    'upload.uploading': 'Uploading...',

    // Text
    'text.characterCounter': 'characters',

    // English translations (add to the 'en' object):
'comments.title': 'Comments ({count})',
'comments.placeholder': 'Share your memories or knowledge about this photo...',
'comments.postComment': 'Post Comment',
'comments.signInMessage': 'Sign in to share your memories and comments',
'comments.signInToComment': 'Sign In to Comment',
'comments.signInSuccess': 'Successfully signed in! You can now comment.',
'comments.signInError': 'Failed to sign in. Please try again.',
'comments.commentAdded': 'Your comment has been added!',
'comments.noComments': 'No comments yet. Be the first to share your thoughts!',

// English translations (add to the 'en' object):
'locationMap.photoLocation': 'Photo Location',
'locationMap.viewOnMap': 'View on Map',
'locationMap.viewPhoto': 'View photo',
'locationMap.location': 'Location',
'locationMap.address': 'Address',
'locationMap.nearbyPhotos': 'Nearby photos',

// English translations (add to the 'en' object):
'mapView.memoryMap': 'Memory Map',
'mapView.exploreCroatian': 'Explore Croatian heritage through interactive map',
'mapView.loadingMemoryMap': 'Loading memory map...',
'mapView.noLocatedPhotos': 'No Located Photos Yet',
'mapView.photosWillAppear': 'Photos will appear on the map once they are uploaded with specific addresses.',
'mapView.addPhotosTo': 'Add Photos to {location}',
'mapView.filters': 'Filters:',
'mapView.allDecades': 'All decades',
'mapView.searchByLocation': 'Search by location or address...',
'mapView.showing': 'Showing {filtered} of {total} photos',
'mapView.photosOnMap': 'Photos on Map',
'mapView.viewDetails': 'View Details',
'mapView.photosInArea': '{count} Photos in this area',
'mapView.morePhotos': '+{count} more photos',
'mapView.locatedPhotos': 'Located Photos',
'mapView.cities': 'Cities',
'mapView.specificAddresses': 'Specific Addresses',
'mapView.differentDecades': 'Different Decades',
'mapView.debugInfo': '🔍 Debug Info:',
'mapView.totalPhotos': 'Total photos:',
'mapView.filtered': 'Filtered:',
'mapView.currentZoom': 'Current zoom:',
'mapView.clusters': 'Clusters:',
'mapView.individualMarkers': 'Individual markers:',
'mapView.howClusteringWorks': '📍 How clustering works',
'mapView.clusteringDesc1': '• When multiple photos are close together, they group into numbered clusters',
'mapView.clusteringDesc2': '• Click on a cluster to see all photos in that area',
'mapView.clusteringDesc3': '• Zoom in to see individual photo markers',
'mapView.clusteringDesc4': '• Upload more photos to the same address to see clustering in action!',

// About page
'about.title': 'About Vremeplov',
'about.subtitle': 'Preserving Croatian heritage, one memory at a time',
'about.ourMission': 'Our Mission',
'about.missionText1': 'Vremeplov.hr is a digital platform dedicated to preserving and sharing the rich visual history of Croatian cities and villages. We believe that every photograph tells a story, and every story deserves to be preserved for future generations.',
'about.missionText2': 'Our mission is to create a comprehensive archive of historical photographs from across Croatia, making these precious memories accessible to everyone while fostering a deeper connection to our heritage.',
'about.howWeHelp': 'How We Help Communities',
'about.digitalPreservation': 'Digital Preservation',
'about.digitalPreservationDesc': 'We provide a secure, digital home for historical photographs that might otherwise be lost to time.',
'about.localHistory': 'Local History Documentation',
'about.localHistoryDesc': 'Each location gets its own dedicated space, creating comprehensive visual histories of Croatian places.',
'about.communityConnection': 'Community Connection',
'about.communityConnectionDesc': 'People can tag relatives, share stories, and connect with others who share their heritage.',
'about.culturalHeritage': 'Cultural Heritage',
'about.culturalHeritageDesc': 'We help communities maintain their cultural identity by preserving visual memories.',
'about.aboutDeveloper': 'About the Developer',
'about.developerText1': 'Vremeplov.hr was created by Kruno Žagar, a passionate developer committed to preserving Croatian heritage through technology. Understanding the importance of our cultural history and the risk of losing precious memories, Kruno developed this platform to ensure that future generations can explore and connect with their roots.',
'about.developerText2': 'This project represents a personal commitment to giving back to the community by providing a valuable service that helps preserve our shared cultural heritage.',
'about.getInvolved': 'Get Involved',
'about.getInvolvedText': 'Help us build the most comprehensive archive of Croatian historical photographs. Your contributions make a difference in preserving our heritage.',
'about.startContributing': 'Start Contributing',

// Privacy page
'privacy.title': 'Privacy Policy',
'privacy.subtitle': 'How we protect and handle your data',
'privacy.dataCollection': 'Data Collection and Storage',
'privacy.dataCollectionText1': 'When you upload photos to Vremeplov.hr, we collect and store the following information:',
'privacy.dataCollectionList1': 'Historical photographs you choose to share',
'privacy.dataCollectionList2': 'Photo metadata (year, location, description, author)',
'privacy.dataCollectionList3': 'Comments and tags you add to photos',
'privacy.dataCollectionList4': 'Basic usage analytics to improve the platform',
'privacy.dataCollectionText2': 'All uploaded photos are stored securely in our database and are made publicly available on the platform to fulfill our mission of preserving Croatian heritage. By uploading content, you grant permission for it to be displayed on Vremeplov.hr.',
'privacy.dataProtection': 'Data Protection',
'privacy.dataProtectionText1': 'We take the security of your data seriously. All uploads are processed through secure connections and stored using industry-standard security measures.',
'privacy.dataProtectionText2': 'We do not sell, trade, or otherwise transfer your personal information to third parties. Your data is used solely for the purpose of operating and improving Vremeplov.hr.',
'privacy.contentRemoval': 'Content Removal',
'privacy.contentRemovalText1': 'If you need to remove photos or other content you\'ve uploaded, you can request deletion by contacting us with a valid reason. We will review each request and remove content when appropriate.',
'privacy.contentRemovalText2': 'Valid reasons for content removal include:',
'privacy.contentRemovalList1': 'Copyright concerns or ownership disputes',
'privacy.contentRemovalList2': 'Privacy concerns regarding individuals in photos',
'privacy.contentRemovalList3': 'Inaccurate or misleading information',
'privacy.contentRemovalList4': 'Personal or family requests for removal',
'privacy.privacyQuestions': 'Privacy Questions',
'privacy.privacyQuestionsText': 'If you have questions about this privacy policy or concerns about your data, please contact us at:',
'privacy.policyUpdates': 'Policy Updates',
'privacy.policyUpdatesText': 'This privacy policy may be updated from time to time. Any changes will be posted on this page with an updated revision date. Continued use of Vremeplov.hr after changes constitutes acceptance of the updated policy.',
'privacy.lastUpdated': 'Last updated: {date}',

// Terms page
'terms.title': 'Terms of Service',
'terms.subtitle': 'Rules and guidelines for using Vremeplov.hr',
'terms.acceptance': 'Acceptance of Terms',
'terms.acceptanceText': 'By accessing and using Vremeplov.hr, you accept and agree to be bound by these terms and conditions. If you do not agree to these terms, please do not use our platform.',
'terms.contentCopyright': 'Content and Copyright',
'terms.contentText1': 'When uploading content to Vremeplov.hr, you must ensure that:',
'terms.contentList1': 'You own the rights to the photographs or have permission to share them',
'terms.contentList2': 'The content is historically accurate to the best of your knowledge',
'terms.contentList3': 'Photos are appropriate and respectful to all individuals depicted',
'terms.contentList4': 'Content does not violate any third-party rights or applicable laws',
'terms.contentText2': 'By uploading content, you grant Vremeplov.hr a non-exclusive license to display, store, and share your contributions as part of our cultural heritage preservation mission.',
'terms.userResponsibilities': 'User Responsibilities',
'terms.userText1': 'As a user of Vremeplov.hr, you agree to:',
'terms.userList1': 'Provide accurate information when uploading photos and metadata',
'terms.userList2': 'Use the platform respectfully and not engage in harassment or inappropriate behavior',
'terms.userList3': 'Respect the privacy and dignity of individuals in historical photographs',
'terms.userList4': 'Report any content that violates these terms or appears inappropriate',
'terms.userList5': 'Not attempt to damage, disable, or impair the platform\'s functionality',
'terms.prohibited': 'Prohibited Activities',
'terms.prohibitedText': 'The following activities are strictly prohibited on Vremeplov.hr:',
'terms.prohibitedList1': 'Uploading copyrighted material without permission',
'terms.prohibitedList2': 'Sharing false or misleading historical information',
'terms.prohibitedList3': 'Uploading inappropriate, offensive, or harmful content',
'terms.prohibitedList4': 'Attempting to hack, spam, or otherwise misuse the platform',
'terms.prohibitedList5': 'Commercial use without explicit permission',
'terms.availability': 'Platform Availability',
'terms.availabilityText': 'While we strive to maintain 24/7 availability, Vremeplov.hr may occasionally be unavailable due to maintenance, updates, or technical issues. We are not liable for any inconvenience caused by temporary unavailability.',
'terms.liability': 'Limitation of Liability',
'terms.liabilityText': 'Vremeplov.hr is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the platform, including but not limited to data loss, service interruptions, or inaccuracies in user-contributed content.',
'terms.questionsAbout': 'Questions About Terms',
'terms.questionsText': 'If you have questions about these terms of service, please contact us at',
'terms.termsUpdates': 'Terms Updates',
'terms.termsUpdatesText': 'These terms may be updated from time to time. Changes will be posted on this page. Continued use of the platform after changes constitutes acceptance of the updated terms.',

// Contact page
'contact.title': 'Contact Us',
'contact.subtitle': 'Get in touch with the Vremeplov.hr team',
'contact.getInTouch': 'Get in Touch',
'contact.getInTouchText': 'We\'d love to hear from you! Whether you have questions, suggestions, or need help, we\'re here to assist you.',
'contact.ourEmail': 'Our dedicated email for all Vremeplov.hr inquiries',
'contact.whatCanWeHelp': 'What Can We Help You With?',
'contact.technicalSupport': 'Technical Support',
'contact.techList1': '• Issues uploading photos',
'contact.techList2': '• Website functionality problems',
'contact.techList3': '• Account or login assistance',
'contact.techList4': '• Mobile compatibility issues',
'contact.contentManagement': 'Content Management',
'contact.contentList1': '• Request photo removal',
'contact.contentList2': '• Report inappropriate content',
'contact.contentList3': '• Correct photo information',
'contact.contentList4': '• Copyright concerns',
'contact.partnership': 'Partnership & Collaboration',
'contact.partnershipList1': '• Museum partnerships',
'contact.partnershipList2': '• Community collaborations',
'contact.partnershipList3': '• Educational institution projects',
'contact.partnershipList4': '• Media and press inquiries',
'contact.generalFeedback': 'General Feedback',
'contact.feedbackList1': '• Suggestions for improvement',
'contact.feedbackList2': '• Feature requests',
'contact.feedbackList3': '• Share your story',
'contact.feedbackList4': '• General questions about the project',
'contact.responseTime': 'Response Time',
'contact.responseTimeText': 'We typically respond to all inquiries within 24-48 hours. For urgent issues, please mark your email as "URGENT" in the subject line. We appreciate your patience and look forward to helping you contribute to preserving Croatian heritage.',
'contact.otherWays': 'Other Ways to Connect',
'contact.otherWaysText': 'While email is our primary contact method, you can also reach out through our social media channels or community forums when they become available.',
'contact.newsletter': 'Follow our development and updates by subscribing to our newsletter (coming soon)',
  },
  hr: {
    // Navigation
    'nav.home': 'Početna',
    'nav.about': 'O nama',
    'nav.contact': 'Kontakt',
    'nav.dashboard': 'Kontrolna ploča',
    'nav.login': 'Prijava',
    'nav.logout': 'Odjava',
    'nav.admin': 'Admin',
    'nav.memoryMap': 'Memorijska karta',
    
    // Home page
    'home.title': 'Hrvatske povijesne fotografije',
    'home.subtitle': 'Sačuvajte i podijelite bogatu fotografsku baštinu Hrvatske',
    'home.description': 'Otkrijte povijesne fotografije iz cijele Hrvatske. Podijelite svoje obiteljske fotografije i pomozite sačuvati našu kulturnu memoriju za buduće generacije.',
    'home.upload': 'Učitaj fotografiju',
    'home.explore': 'Istraži galeriju',
    'home.recent': 'Nedavne fotografije',
    'home.reconnectTitle': 'Povežite se sa svojom baštinom',
    'home.discoverTitle': 'Otkrijte mjesta',
    'home.discoverDesc': 'Pretražite bilo koji grad ili selo u hrvatskoj i istražite njegovu vizualnu povijest na našoj interaktivnoj karti.',
    'home.preserveTitle': 'Sačuvajte sjećanja',
    'home.preserveDesc': 'Učitajte i podijelite povijesne fotografije i videozapise iz svojih obiteljskih arhiva.',
    'home.connectTitle': 'Povežite ljude',
    'home.connectDesc': 'Označite osobe, podijelite priče i povežite se sa svojom zajednicom.',
    'home.exploreCroatiaTitle': 'Istražite Hrvatsku kroz vrijeme',
    'home.exploreCroatiaDesc': 'Otkrijte povijesne fotografije geografski i vidite kako su vaša omiljena mjesta izgledala kroz povijest.',
    'home.exploreMemoryMap': 'Istražite memorijsku kartu',
    'home.glimpseTitle': 'Pogled u prošlost',
    'home.glimpseDesc': 'Pregledajte našu kolekciju povijesnih fotografija iz različitih hrvatskih lokacija.',
    'home.startJourneyTitle': 'Započnite svoje putovanje kroz vrijeme',
    'home.startJourneyDesc': 'Pridružite se našoj zajednici i pomozite sačuvati vizualnu povijest Hrvatske za buduće generacije.',
    
    // Photo Detail Page
    'photoDetail.loading': 'Učitavanje sjećanja...',
    'photoDetail.notFound': 'Fotografija nije pronađena',
    'photoDetail.notFoundDesc': 'Traženo sjećanje nije moglo biti pronađeno.',
    'photoDetail.returnHome': 'Vrati se na početnu',
    'photoDetail.aboutPhoto': 'O ovoj fotografiji',
    'photoDetail.year': 'Godina',
    'photoDetail.author': 'Autor',
    'photoDetail.location': 'Lokacija',
    'photoDetail.uploadedBy': 'Učitao',
    'photoDetail.on': 'dana',
    'photoDetail.taggedPeople': 'Označene osobe',
    'photoDetail.historicalContext': 'Povijesni kontekst',
    'photoDetail.relatedPhotos': 'Povezane fotografije',
    'photoDetail.morePhotosFrom': 'Više fotografija iz',
    'photoDetail.views': 'pogleda',
    'photoDetail.likes': 'sviđanja',
    'photoDetail.likePhoto': 'Sviđa mi se',
    'photoDetail.unlikePhoto': 'Ne sviđa mi se',
    'photoDetail.signInToLike': 'Prijavite se za ocjenu',
    'photoDetail.signInMessage': 'Molimo prijavite se da biste mogli ocijeniti fotografije i komunicirati sa sjećanjima',
    'photoDetail.tagPerson': 'Označi osobu',
    'photoDetail.clickToPosition': 'Kliknite na fotografiju da postavite oznaku',
    'photoDetail.personName': 'Ime osobe',
    'photoDetail.saveTag': 'Spremi oznaku',
    'photoDetail.cancel': 'Odustani',
    'photoDetail.positionSelected': 'Pozicija je odabrana. Molimo unesite ime za oznaku.',
    'photoDetail.enterNameAndPosition': 'Molimo unesite ime i odaberite poziciju na slici',
    'photoDetail.taggedSuccess': 'Osoba je uspješno označena!',
    'photoDetail.tagSaveFailed': 'Neuspješno dodavanje oznake',
    'photoDetail.commentAdded': 'Komentar je uspješno dodan!',
    'photoDetail.commentFailed': 'Neuspješno dodavanje komentara',
    'photoDetail.photoLiked': 'Fotografija označena kao sviđa!',
    'photoDetail.photoUnliked': 'Fotografija označena kao ne sviđa!',
    'photoDetail.likeFailed': 'Neuspješno ažuriranje ocjene',
    'photoDetail.historicalContextDesc': 'Ovo razdoblje je obilježilo značajan razvoj u lokalnoj povijesti mjesta {location}. Mnoge slične fotografije iz tog doba dokumentiraju mijenjajući se krajolik i svakodnevni život stanovnika.',
    'photoDetail.defaultDescription': 'Ova povijesna fotografija iz {year}. prikazuje {description} u {location}. Doprinijela ju je u arhiv Vremeplov.hr osoba {author}.',
    
    // Upload
    'upload.title': 'Podijeli povijesnu fotografiju',
    'upload.select': 'Odaberi fotografiju',
    'upload.drag': 'Povuci i spusti fotografiju ovdje ili klikni za odabir',
    'upload.year': 'Godina',
    'upload.author': 'Autor/Fotograf',
    'upload.description': 'Kratki opis',
    'upload.story': 'Detaljna priča',
    'upload.submit': 'Učitaj fotografiju',
    'upload.cancel': 'Odustani',
    'upload.success': 'Fotografija je uspješno učitana!',
    'upload.error': 'Neuspješno učitavanje fotografije',
    'upload.offline': 'Niste povezani s internetom',
    'upload.tagPerson': 'Označi osobu',
    'upload.enterName': 'Unesite ime osobe',
    'upload.saveTag': 'Spremi oznaku',
    'upload.cancelTag': 'Odustani',
    
    // Gallery
    'gallery.noPhotos': 'Nema fotografija',
    'gallery.noPhotosDesc': 'Budite prvi koji će podijeliti povijesnu fotografiju i pomoći sačuvati hrvatsku baštinu!',
    'gallery.loading': 'Učitavanje fotografija...',
    
    // Photo detail
    'photo.year': 'Godina',
    'photo.author': 'Autor',
    'photo.location': 'Lokacija',
    'photo.story': 'Priča',
    'photo.taggedPeople': 'Označene osobe',
    'photo.comments': 'Komentari',
    'photo.addComment': 'Dodaj komentar',
    
    // Auth
    'auth.signInGoogle': 'Prijavite se s Googleom',
    'auth.signOut': 'Odjava',
    'auth.signInSuccess': 'Uspješno ste se prijavili!',
    'auth.signOutSuccess': 'Uspješno ste se odjavili!',
    'auth.adminLogin': 'Admin prijava',
    'auth.email': 'Email',
    'auth.password': 'Lozinka',
    
    // Common
    'common.of': 'od',
    'common.save': 'Spremi',
    'common.cancel': 'Odustani',
    'common.edit': 'Uredi',
    'common.delete': 'Obriši',
    'common.loading': 'Učitavanje...',
    'common.error': 'Greška',
    'common.success': 'Uspjeh',
    'common.required': 'Obavezno',
    'common.optional': 'Neobavezno',
    
    // Footer
    'footer.about': 'O nama',
    'footer.contact': 'Kontakt',
    'footer.privacy': 'Pravila privatnosti',
    'footer.terms': 'Uvjeti korištenja',
    'footer.rights': 'Sva prava pridržana',
    'footer.tagline': 'Čuvamo hrvatsku baštinu, jedno sjećanje po jedno.',

    // SearchBar
    'search.placeholder': 'Pretražite grad ili selo...',
    'search.button': 'Pretraži',
    'search.inputPlaceholder': 'Pretražite lokaciju...',
    'search.noLocations': 'Nema pronađenih lokacija',

    // Location stranica
    'location.exploreHistory': 'Istražite povijest',
    'location.throughPhotos': 'kroz fotografije i sjećanja',
    'location.photos': 'fotografija',
    'location.addMemory': 'Dodaj sjećanje',
    'location.signInToAdd': 'Prijavite se za dodavanje',
    'location.searchPlaceholder': 'Pretražite fotografije, opise, autore ili oznake...',
    'location.filters': 'Filtri',
    'location.clear': 'Očisti',
    'location.timePeriod': 'Vremensko razdoblje',
    'location.allYears': 'Sve godine',
    'location.photoType': 'Tip fotografije',
    'location.sortBy': 'Sortiraj po',
    'location.showing': 'Prikazano',
    'location.matching': 'koji odgovaraju',
    'location.from': 'iz',
    'location.in': 'u',
    'location.noPhotosFound': 'Nema pronađenih fotografija',
    'location.tryAdjusting': 'Pokušajte prilagoditi filtre ili pojmove pretrage.',
    'location.beFirst': 'Budite prvi koji će podijeliti povijesnu fotografiju ove lokacije!',
    'location.clearAllFilters': 'Očisti sve filtre',
    'location.loadingMemories': 'Učitavanje sjećanja...',
    'location.loadMoreMemories': 'Učitaj više sjećanja',
    
    // Photo types
    'photoType.allTypes': 'Svi tipovi',
    'photoType.street': 'Ulični prizori',
    'photoType.building': 'Zgrade', 
    'photoType.people': 'Ljudi',
    'photoType.event': 'Događaji',
    'photoType.nature': 'Priroda',
    
    // Sort options
    'sort.newest': 'Najnovije prvo',
    'sort.oldest': 'Najstarije prvo',
    'sort.popular': 'Najpopularnije',
    'sort.yearNewest': 'Godina (najnovije)',
    'sort.yearOldest': 'Godina (najstarije)',
    
    // PhotoUpload komponenta
    'upload.addPhotoTo': 'Dodaj povijesnu fotografiju u',
    'upload.clickToUpload': 'Kliknite za učitavanje povijesne fotografije',
    'upload.fileTypes': 'PNG, JPG, JPEG do 5MB',
    'upload.specificAddress': 'Specifična adresa u',
    'upload.optional': '(Neobavezno)',
    'upload.searchAddress': 'Pretražite ulicu, znamenitost ili zgradu...',
    'upload.trySearching': 'Pokušajte pretražiti',
    'upload.selectYear': 'Odaberite godinu',
    'upload.whoTookPhoto': 'Tko je snimio ovu fotografiju?',
    'upload.location': 'Lokacija',
    'upload.briefDescription': 'Kratki opis fotografije',
    'upload.detailedStory': 'Detaljna priča (Neobavezno)',
    'upload.shareStory': 'Podijelite priču iza ove fotografije, povijesni kontekst ili osobna sjećanja...',
    'upload.fillRequired': 'Ispunite obavezna polja',
    'upload.shareMemory': 'Podijeli sjećanje',
    'upload.noConnection': 'Nema konekcije',
    'upload.uploading': 'Učitavanje...',

     // Text
    'text.characterCounter': 'znakova',

    // Croatian translations (add to the 'hr' object):
'comments.title': 'Komentari ({count})',
'comments.placeholder': 'Podijelite svoja sjećanja ili znanje o ovoj fotografiji...',
'comments.postComment': 'Objavi komentar',
'comments.signInMessage': 'Prijavite se da podijelite svoja sjećanja i komentare',
'comments.signInToComment': 'Prijavite se za komentiranje',
'comments.signInSuccess': 'Uspješno ste se prijavili! Sada možete komentirati.',
'comments.signInError': 'Neuspjeh pri prijavi. Molimo pokušajte ponovno.',
'comments.commentAdded': 'Vaš komentar je dodan!',
'comments.noComments': 'Još nema komentara. Budite prvi koji će podijeliti svoje misli!',

// Croatian translations (add to the 'hr' object):
'locationMap.photoLocation': 'Lokacija fotografije',
'locationMap.viewOnMap': 'Pogledaj na karti',
'locationMap.viewPhoto': 'Pogledaj fotografiju',
'locationMap.location': 'Lokacija',
'locationMap.address': 'Adresa',
'locationMap.nearbyPhotos': 'Obližnje fotografije',

// Croatian translations (add to the 'hr' object):
'mapView.memoryMap': 'Memorijska karta',
'mapView.exploreCroatian': 'Istražite hrvatsku baštinu kroz interaktivnu kartu',
'mapView.loadingMemoryMap': 'Učitavanje memorijske karte...',
'mapView.noLocatedPhotos': 'Još nema lociranih fotografija',
'mapView.photosWillAppear': 'Fotografije će se pojaviti na karti kada budu učitane s određenim adresama.',
'mapView.addPhotosTo': 'Dodaj fotografije u {location}',
'mapView.filters': 'Filtri:',
'mapView.allDecades': 'Sva desetljeća',
'mapView.searchByLocation': 'Pretraži po lokaciji ili adresi...',
'mapView.showing': 'Prikazano {filtered} od {total} fotografija',
'mapView.photosOnMap': 'Fotografije na karti',
'mapView.viewDetails': 'Pogledaj detalje',
'mapView.photosInArea': '{count} fotografija u ovom području',
'mapView.morePhotos': '+{count} fotografija više',
'mapView.locatedPhotos': 'Locirane fotografije',
'mapView.cities': 'Gradovi',
'mapView.specificAddresses': 'Specifične adrese',
'mapView.differentDecades': 'Različita desetljeća',
'mapView.debugInfo': '🔍 Debug informacije:',
'mapView.totalPhotos': 'Ukupno fotografija:',
'mapView.filtered': 'Filtrirano:',
'mapView.currentZoom': 'Trenutni zoom:',
'mapView.clusters': 'Klasteri:',
'mapView.individualMarkers': 'Pojedinačni markeri:',
'mapView.howClusteringWorks': '📍 Kako funkcionira klasteriranje',
'mapView.clusteringDesc1': '• Kada je više fotografija blizu jedna drugoj, grupiraju se u numerirane klastere',
'mapView.clusteringDesc2': '• Kliknite na klaster da vidite sve fotografije u tom području',
'mapView.clusteringDesc3': '• Uvećajte za prikaz pojedinačnih markera fotografija',
'mapView.clusteringDesc4': '• Učitajte više fotografija na istu adresu da vidite klasteriranje u akciji!',

// About page
'about.title': 'O Vremeplovu',
'about.subtitle': 'Čuvamo hrvatsku baštinu, jedno sjećanje po jedno',
'about.ourMission': 'Naša misija',
'about.missionText1': 'Vremeplov.hr je digitalna platforma posvećena čuvanju i dijeljenju bogate vizualne povijesti hrvatskih gradova i sela. Vjerujemo da svaka fotografija priča priču i da svaka priča zaslužuje biti sačuvana za buduće generacije.',
'about.missionText2': 'Naša misija je stvoriti sveobuhvatan arhiv povijesnih fotografija iz cijele Hrvatske, učiniti ova dragocjena sjećanja dostupnima svima te potaknuti dublju povezanost s našom baštinom.',
'about.howWeHelp': 'Kako pomagamo zajednicama',
'about.digitalPreservation': 'Digitalno očuvanje',
'about.digitalPreservationDesc': 'Pružamo siguran digitalni dom za povijesne fotografije koje bi inače mogle biti izgubljene u vremenu.',
'about.localHistory': 'Dokumentiranje lokalne povijesti',
'about.localHistoryDesc': 'Svaka lokacija dobiva svoj vlastiti prostor, stvarajući sveobuhvatne vizualne povijesti hrvatskih mjesta.',
'about.communityConnection': 'Povezivanje zajednice',
'about.communityConnectionDesc': 'Ljudi mogu označiti rodbinu, podijeliti priče i povezati se s drugima koji dijele njihovu baštinu.',
'about.culturalHeritage': 'Kulturna baština',
'about.culturalHeritageDesc': 'Pomagamo zajednicama održati njihov kulturni identitet čuvanjem vizualnih sjećanja.',
'about.aboutDeveloper': 'O developeru',
'about.developerText1': 'Vremeplov.hr je stvorio Kruno Žagar, strastveni developer posvećen čuvanju hrvatske baštine kroz tehnologiju. Razumijevajući važnost naše kulturne povijesti i opasnost gubitka dragocjenih sjećanja, Kruno je razvio ovu platformu kako bi osigurao da buduće generacije mogu istraživati i povezivati se sa svojim korijenima.',
'about.developerText2': 'Ovaj projekt predstavlja osobnu predanost vraćanju zajednici pružanjem vrijedne usluge koja pomaže u čuvanju naše zajedničke kulturne baštine.',
'about.getInvolved': 'Uključite se',
'about.getInvolvedText': 'Pomozite nam izgraditi najsveobuhvatniji arhiv hrvatskih povijesnih fotografija. Vaši doprinosi čine razliku u čuvanju naše baštine.',
'about.startContributing': 'Počnite doprinositi',

// Privacy page
'privacy.title': 'Pravila privatnosti',
'privacy.subtitle': 'Kako štitimo i rukujemo vašim podacima',
'privacy.dataCollection': 'Prikupljanje i čuvanje podataka',
'privacy.dataCollectionText1': 'Kad učitate fotografije na Vremeplov.hr, prikupljamo i čuvamo sljedeće informacije:',
'privacy.dataCollectionList1': 'Povijesne fotografije koje odaberete podijeliti',
'privacy.dataCollectionList2': 'Metapodatke fotografija (godina, lokacija, opis, autor)',
'privacy.dataCollectionList3': 'Komentare i oznake koje dodate fotografijama',
'privacy.dataCollectionList4': 'Osnovnu analitiku korištenja za poboljšanje platforme',
'privacy.dataCollectionText2': 'Sve učitane fotografije se sigurno čuvaju u našoj bazi podataka i javno su dostupne na platformi kako bi ispunile našu misiju čuvanja hrvatske baštine. Učitavanjem sadržaja, dajete dozvolu za prikazivanje na Vremeplov.hr.',
'privacy.dataProtection': 'Zaštita podataka',
'privacy.dataProtectionText1': 'Ozbiljno shvaćamo sigurnost vaših podataka. Sva učitavanja se obrađuju kroz sigurne veze i čuvaju koristeći standardne sigurnosne mjere industrije.',
'privacy.dataProtectionText2': 'Ne prodajemo, mijenjamo ili prenošamo vaše osobne informacije trećim stranama. Vaši podaci se koriste isključivo za rad i poboljšanje Vremeplov.hr.',
'privacy.contentRemoval': 'Uklanjanje sadržaja',
'privacy.contentRemovalText1': 'Ako trebate ukloniti fotografije ili drugi sadržaj koji ste učitali, možete zatražiti brisanje kontaktirajući nas s valjanim razlogom. Revizirat ćemo svaki zahtjev i ukloniti sadržaj kad je to prikladno.',
'privacy.contentRemovalText2': 'Valjani razlozi za uklanjanje sadržaja uključuju:',
'privacy.contentRemovalList1': 'Zabrinutosti oko autorskih prava ili sporovi o vlasništvu',
'privacy.contentRemovalList2': 'Zabrinutosti oko privatnosti osoba na fotografijama',
'privacy.contentRemovalList3': 'Netočne ili obmanjujuće informacije',
'privacy.contentRemovalList4': 'Osobni ili obiteljski zahtjevi za uklanjanjem',
'privacy.privacyQuestions': 'Pitanja o privatnosti',
'privacy.privacyQuestionsText': 'Ako imate pitanja o ovim pravilima privatnosti ili zabrinutosti oko svojih podataka, molimo kontaktirajte nas na:',
'privacy.policyUpdates': 'Ažuriranja pravila',
'privacy.policyUpdatesText': 'Ova pravila privatnosti mogu se povremeno ažurirati. Sve promjene bit će objavljene na ovoj stranici s ažuriranim datumom revizije. Nastavak korištenja Vremeplov.hr nakon promjena predstavlja prihvaćanje ažuriranih pravila.',
'privacy.lastUpdated': 'Zadnje ažurirano: {date}',

// Terms page
'terms.title': 'Uvjeti korištenja',
'terms.subtitle': 'Pravila i smjernice za korištenje Vremeplov.hr',
'terms.acceptance': 'Prihvaćanje uvjeta',
'terms.acceptanceText': 'Pristupanjem i korištenjem Vremeplov.hr, prihvaćate i slažete se biti vezani ovim uvjetima i odredbama. Ako se ne slažete s ovim uvjetima, molimo ne koristite našu platformu.',
'terms.contentCopyright': 'Sadržaj i autorska prava',
'terms.contentText1': 'Kada učitavate sadržaj na Vremeplov.hr, morate osigurati da:',
'terms.contentList1': 'Posjedujete prava na fotografije ili imate dozvolu za njihovo dijeljenje',
'terms.contentList2': 'Sadržaj je povijesno točan prema vašem najboljem znanju',
'terms.contentList3': 'Fotografije su prikladne i poštuju sve prikazane osobe',
'terms.contentList4': 'Sadržaj ne krši prava treće strane ili važeće zakone',
'terms.contentText2': 'Učitavanjem sadržaja, dajete Vremeplov.hr neekskluzivnu licencu za prikazivanje, čuvanje i dijeljenje vaših doprinosa kao dijela naše misije očuvanja kulturne baštine.',
'terms.userResponsibilities': 'Odgovornosti korisnika',
'terms.userText1': 'Kao korisnik Vremeplov.hr, slažete se da ćete:',
'terms.userList1': 'Pružiti točne informacije kad učitavate fotografije i metapodatke',
'terms.userList2': 'Koristiti platformu s poštovanjem i ne sudjelovati u uznemiravanje ili neprikladno ponašanje',
'terms.userList3': 'Poštovati privatnost i dostojanstvo osoba na povijesnim fotografijama',
'terms.userList4': 'Prijaviti sadržaj koji krši ove uvjete ili se čini neprikladan',
'terms.userList5': 'Ne pokušavati oštetiti, onemogućiti ili narušiti funkcionalnost platforme',
'terms.prohibited': 'Zabranjene aktivnosti',
'terms.prohibitedText': 'Sljedeće aktivnosti su strogo zabranjene na Vremeplov.hr:',
'terms.prohibitedList1': 'Učitavanje materijala zaštićenog autorskim pravima bez dozvole',
'terms.prohibitedList2': 'Dijeljenje lažnih ili obmanjujućih povijesnih informacija',
'terms.prohibitedList3': 'Učitavanje neprikladnog, uvredljivog ili štetnog sadržaja',
'terms.prohibitedList4': 'Pokušaji hakiranje, špam ili drugo zlouporaba platforme',
'terms.prohibitedList5': 'Komercijalna upotreba bez eksplicitne dozvole',
'terms.availability': 'Dostupnost platforme',
'terms.availabilityText': 'Iako nastojimo održati dostupnost 24/7, Vremeplov.hr može povremeno biti nedostupan zbog održavanja, ažuriranja ili tehničkih problema. Nismo odgovorni za neugodnosti uzrokovane privremenom nedostupnošću.',
'terms.liability': 'Ograničenje odgovornosti',
'terms.liabilityText': 'Vremeplov.hr se pruža "kao što jest" bez ikakvih jamstava. Nismo odgovorni za štete nastale vašim korištenjem platforme, uključujući ali ne ograničavajući se na gubitak podataka, prekide usluge ili netočnosti u sadržaju korisnika.',
'terms.questionsAbout': 'Pitanja o uvjetima',
'terms.questionsText': 'Ako imate pitanja o ovim uvjetima korištenja, molimo kontaktirajte nas na',
'terms.termsUpdates': 'Ažuriranja uvjeta',
'terms.termsUpdatesText': 'Ovi uvjeti se mogu povremeno ažurirati. Promjene će biti objavljene na ovoj stranici. Nastavak korištenja platforme nakon promjena predstavlja prihvaćanje ažuriranih uvjeta.',

// Contact page
'contact.title': 'Kontakt',
'contact.subtitle': 'Stupite u kontakt s Vremeplov.hr timom',
'contact.getInTouch': 'Stupite u kontakt',
'contact.getInTouchText': 'Volio bismo čuti od vas! Bilo da imate pitanja, prijedloge ili trebate pomoć, tu smo da vam pomognemo.',
'contact.ourEmail': 'Naš e-mail za sve Vremeplov.hr upite',
'contact.whatCanWeHelp': 'S čime vam možemo pomoći?',
'contact.technicalSupport': 'Tehnička podrška',
'contact.techList1': '• Problemi s učitavanjem fotografija',
'contact.techList2': '• Problemi s funkcionalnosti web stranice',
'contact.techList3': '• Pomoć s računom ili prijavom',
'contact.techList4': '• Problemi s mobilnom kompatibilnosti',
'contact.contentManagement': 'Upravljanje sadržajem',
'contact.contentList1': '• Zahtjev za uklanjanje fotografija',
'contact.contentList2': '• Prijaviti neprikladan sadržaj',
'contact.contentList3': '• Ispraviti informacije o fotografiji',
'contact.contentList4': '• Zabrinutosti oko autorskih prava',
'contact.partnership': 'Partnerstvo i suradnja',
'contact.partnershipList1': '• Partnerstva s muzejima',
'contact.partnershipList2': '• Suradnje sa zajednicom',
'contact.partnershipList3': '• Projekti obrazovnih institucija',
'contact.partnershipList4': '• Upiti medija i tiska',
'contact.generalFeedback': 'Općenite povratne informacije',
'contact.feedbackList1': '• Prijedlozi za poboljšanje',
'contact.feedbackList2': '• Zahtjevi za novim funkcijama',
'contact.feedbackList3': '• Podijelite svoju priču',
'contact.feedbackList4': '• Općenita pitanja o projektu',
'contact.responseTime': 'Vrijeme odgovora',
'contact.responseTimeText': 'Tipično odgovaramo na sve upite unutar 24-48 sati. Za hitne slučajeve, molimo označite svoj e-mail kao "HITNO" u predmetu. Cijenimo vašu strpljivost i radujemo se što vam možemo pomoći doprinijeti čuvanju hrvatske baštine.',
'contact.otherWays': 'Drugi načini povezivanja',
'contact.otherWaysText': 'Iako je e-mail naš primarni način kontakta, možete nas kontaktirati i putem naših kanala društvenih mreža ili foruma zajednice kada postanu dostupni.',
'contact.newsletter': 'Pratite naš razvoj i ažuriranja pretplaćivanjem na naš bilten (uskoro)'
  }
};

// Helper function for string interpolation
export const translateWithParams = (t: (key: string) => string, key: string, params: Record<string, string | number>) => {
  let translation = t(key);
  Object.entries(params).forEach(([param, value]) => {
    translation = translation.replace(new RegExp(`{${param}}`, 'g'), String(value));
  });
  return translation;
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Check localStorage first, then browser language, fallback to English
    const saved = localStorage.getItem('language') as Language;
    if (saved) return saved;
    
    const browserLang = navigator.language.toLowerCase();
    return browserLang.startsWith('hr') ? 'hr' : 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const value = {
    language,
    setLanguage,
    t
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};